# Generated by Django 5.1.4 on 2026-02-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="codice_fiscale",
            field=models.CharField(
                blank=True,
                help_text="Codice fiscale italiano (16 caratteri)",
                max_length=16,
                null=True,
                unique=True,
                verbose_name="Codice Fiscale",
            ),
        ),
    ]
