# Generated by Django 6.0 on 2026-02-02 12:31

import automezzi.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automezzi', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='automezzo',
            name='carta_carburante',
            field=models.CharField(blank=True, help_text='Numero carta carburante associata al mezzo', max_length=50),
        ),
        migrations.AddField(
            model_name='automezzo',
            name='pin_carta_carburante',
            field=models.CharField(blank=True, help_text='PIN della carta carburante', max_length=10),
        ),
        migrations.CreateModel(
            name='AffidamentoMezzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inizio', models.DateField(help_text='Data inizio affidamento')),
                ('data_fine', models.DateField(help_text='Data fine prevista affidamento')),
                ('video_stato_vettura', models.FileField(blank=True, help_text='Video dello stato della vettura alla consegna', null=True, upload_to=automezzi.models.affidamento_video_upload_path)),
                ('km_iniziali', models.PositiveIntegerField(help_text='Chilometri alla consegna')),
                ('km_finali', models.PositiveIntegerField(blank=True, help_text='Chilometri al rientro', null=True)),
                ('scopo_viaggio', models.CharField(help_text='Scopo del viaggio / trasferta', max_length=200)),
                ('carburante', models.CharField(choices=[('vuoto', 'Vuoto'), ('1/4', '1/4'), ('1/2', '1/2'), ('3/4', '3/4'), ('pieno', 'Pieno')], help_text='Livello carburante alla consegna', max_length=10)),
                ('note', models.TextField(blank=True, help_text="Note aggiuntive sull'affidamento")),
                ('firma_accettazione', models.BooleanField(default=False, help_text='Firma digitale per accettazione del mezzo')),
                ('token_accettazione', models.UUIDField(editable=False, help_text='Token univoco per il link di accettazione', unique=True)),
                ('data_accettazione', models.DateTimeField(blank=True, help_text='Data e ora di accettazione', null=True)),
                ('stato', models.CharField(choices=[('in_attesa', 'In attesa di accettazione'), ('accettato', 'Accettato'), ('in_corso', 'In corso'), ('completato', 'Completato')], default='in_attesa', max_length=15)),
                ('video_rientro', models.FileField(blank=True, help_text='Video dello stato della vettura al rientro', null=True, upload_to=automezzi.models.affidamento_video_rientro_upload_path)),
                ('note_rientro', models.TextField(blank=True, help_text='Note al rientro del mezzo')),
                ('data_rientro', models.DateTimeField(blank=True, help_text='Data e ora effettiva del rientro', null=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('automezzo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affidamenti', to='automezzi.automezzo')),
                ('creato_da', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affidamenti_creati', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Dipendente a cui viene affidato il mezzo', on_delete=django.db.models.deletion.CASCADE, related_name='affidamenti_mezzo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Affidamento Mezzo',
                'verbose_name_plural': 'Affidamenti Mezzi',
                'ordering': ['-data_creazione'],
            },
        ),
    ]
