# Generated by Django 5.1.4 on 2026-03-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automezzi", "0003_automezzo_carta_carburante_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="affidamentomezzo",
            name="danni_consegna",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista danni presenti alla consegna: [{'area': 'cofano_anteriore', 'x': 50, 'y': 30, 'tipo': 'graffio', 'note': '...'}]",
            ),
        ),
        migrations.AddField(
            model_name="affidamentomezzo",
            name="danni_rientro",
            field=models.JSONField(
                blank=True, default=list, help_text="Lista danni presenti al rientro"
            ),
        ),
    ]
