# Generated by Django 5.1.4 on 2026-03-06 07:53

import automezzi.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anagrafica", "0001_initial"),
        ("automezzi", "0004_add_vehicle_damage_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Gruppo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_gruppo",
                    models.IntegerField(
                        blank=True,
                        help_text="Numero identificativo del gruppo",
                        null=True,
                    ),
                ),
                (
                    "matricola",
                    models.CharField(
                        help_text="Matricola/Seriale del gruppo elettrogeno",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("marca", models.CharField(max_length=50)),
                ("modello", models.CharField(max_length=50)),
                ("anno_produzione", models.PositiveIntegerField()),
                ("attivo", models.BooleanField(default=True)),
                ("disponibile", models.BooleanField(default=True)),
                ("bloccato", models.BooleanField(default=False)),
                ("motivo_blocco", models.TextField(blank=True, null=True)),
                (
                    "potenza_kva",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Potenza apparente in kVA",
                        max_digits=8,
                    ),
                ),
                (
                    "potenza_kw",
                    models.DecimalField(
                        decimal_places=2, help_text="Potenza attiva in kW", max_digits=8
                    ),
                ),
                (
                    "tipo_motore",
                    models.CharField(
                        choices=[
                            ("diesel", "Diesel"),
                            ("benzina", "Benzina"),
                            ("gas", "Gas"),
                            ("ibrido", "Ibrido"),
                        ],
                        default="diesel",
                        max_length=10,
                    ),
                ),
                (
                    "cilindrata",
                    models.PositiveIntegerField(
                        blank=True, help_text="Cilindrata in cc", null=True
                    ),
                ),
                ("numero_cilindri", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "capacita_serbatoio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Capacità serbatoio in litri",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "consumo_orario",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Consumo medio orario in litri/ora",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "tipo_raffreddamento",
                    models.CharField(
                        choices=[
                            ("aria", "Raffreddamento ad Aria"),
                            ("acqua", "Raffreddamento ad Acqua"),
                        ],
                        default="aria",
                        max_length=10,
                    ),
                ),
                (
                    "tensione_uscita",
                    models.CharField(
                        blank=True,
                        help_text="Tensione di uscita (es: 230/400V)",
                        max_length=50,
                    ),
                ),
                (
                    "frequenza",
                    models.CharField(
                        choices=[
                            ("50", "50 Hz"),
                            ("60", "60 Hz"),
                            ("50/60", "50/60 Hz"),
                        ],
                        default="50",
                        max_length=10,
                    ),
                ),
                (
                    "ore_lavoro_attuali",
                    models.PositiveIntegerField(
                        default=0, help_text="Ore di funzionamento totali"
                    ),
                ),
                (
                    "ore_ultima_manutenzione",
                    models.PositiveIntegerField(
                        default=0, help_text="Ore al momento dell'ultima manutenzione"
                    ),
                ),
                (
                    "intervallo_manutenzione_ore",
                    models.PositiveIntegerField(
                        default=250, help_text="Intervallo in ore tra le manutenzioni"
                    ),
                ),
                ("data_ultimo_cambio_olio", models.DateField(blank=True, null=True)),
                (
                    "data_ultimo_cambio_filtro_aria",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "data_ultimo_cambio_filtro_carburante",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "data_ultimo_cambio_filtro_olio",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "data_ultima_revisione_batteria",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "data_ultima_prova_funzionamento",
                    models.DateField(
                        blank=True,
                        help_text="Data dell'ultima prova di funzionamento",
                        null=True,
                    ),
                ),
                (
                    "manuale_uso",
                    models.FileField(
                        blank=True,
                        help_text="Manuale d'uso e manutenzione",
                        null=True,
                        upload_to=automezzi.models.manuale_gruppo_upload_path,
                    ),
                ),
                (
                    "certificato_conformita",
                    models.FileField(
                        blank=True,
                        help_text="Certificato di conformità",
                        null=True,
                        upload_to=automezzi.models.certificato_gruppo_upload_path,
                    ),
                ),
                (
                    "scheda_tecnica",
                    models.FileField(
                        blank=True,
                        help_text="Scheda tecnica del costruttore",
                        null=True,
                        upload_to=automezzi.models.certificato_gruppo_upload_path,
                    ),
                ),
                (
                    "ubicazione",
                    models.CharField(
                        blank=True,
                        help_text="Ubicazione fisica del gruppo",
                        max_length=200,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "assegnato_a",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gruppi_assegnati",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Gruppo Elettrogeno",
                "verbose_name_plural": "Gruppi Elettrogeni",
                "ordering": ["matricola"],
            },
        ),
        migrations.CreateModel(
            name="EventoGruppo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("guasto", "Guasto/avaria"),
                            ("fermo", "Fermo tecnico"),
                            ("surriscaldamento", "Surriscaldamento"),
                            ("mancato_avvio", "Mancato avvio"),
                            ("perdita_olio", "Perdita olio"),
                            ("perdita_carburante", "Perdita carburante"),
                            ("batteria_scarica", "Batteria scarica"),
                            ("altro", "Altro"),
                        ],
                        max_length=30,
                    ),
                ),
                ("data_evento", models.DateField()),
                (
                    "ore_lavoro",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Ore di funzionamento al momento dell'evento",
                        null=True,
                    ),
                ),
                ("descrizione", models.TextField(blank=True)),
                (
                    "costo",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "file_allegato",
                    models.FileField(
                        blank=True,
                        help_text="Foto, verbali, documenti relativi all'evento",
                        null=True,
                        upload_to=automezzi.models.allegato_evento_gruppo_path,
                    ),
                ),
                ("risolto", models.BooleanField(default=False)),
                (
                    "dipendente_coinvolto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eventi_gruppo_coinvolto",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "gruppo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventi_gruppo",
                        to="automezzi.gruppo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento Gruppo",
                "verbose_name_plural": "Eventi Gruppi",
                "ordering": ["-data_evento"],
            },
        ),
        migrations.CreateModel(
            name="AffidamentoGruppo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inizio", models.DateField(help_text="Data inizio affidamento")),
                (
                    "data_fine",
                    models.DateField(help_text="Data fine prevista affidamento"),
                ),
                (
                    "video_stato_gruppo",
                    models.FileField(
                        blank=True,
                        help_text="Video dello stato del gruppo alla consegna",
                        null=True,
                        upload_to=automezzi.models.affidamento_gruppo_video_upload_path,
                    ),
                ),
                (
                    "ore_iniziali",
                    models.PositiveIntegerField(help_text="Ore lavoro alla consegna"),
                ),
                (
                    "ore_finali",
                    models.PositiveIntegerField(
                        blank=True, help_text="Ore lavoro al rientro", null=True
                    ),
                ),
                (
                    "scopo_utilizzo",
                    models.CharField(
                        help_text="Scopo dell'utilizzo / cantiere", max_length=200
                    ),
                ),
                (
                    "destinazione",
                    models.CharField(
                        blank=True,
                        help_text="Luogo di destinazione del gruppo",
                        max_length=200,
                    ),
                ),
                (
                    "carburante",
                    models.CharField(
                        choices=[
                            ("vuoto", "Vuoto"),
                            ("1/4", "1/4"),
                            ("1/2", "1/2"),
                            ("3/4", "3/4"),
                            ("pieno", "Pieno"),
                        ],
                        help_text="Livello carburante alla consegna",
                        max_length=10,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, help_text="Note aggiuntive sull'affidamento"
                    ),
                ),
                (
                    "firma_accettazione",
                    models.BooleanField(
                        default=False, help_text="Dipendente ha accettato l'affidamento"
                    ),
                ),
                (
                    "data_accettazione",
                    models.DateTimeField(
                        blank=True, help_text="Data e ora di accettazione", null=True
                    ),
                ),
                (
                    "stato",
                    models.CharField(
                        choices=[
                            ("in_attesa", "In attesa di accettazione"),
                            ("accettato", "Accettato"),
                            ("in_corso", "In corso"),
                            ("completato", "Completato"),
                        ],
                        default="in_attesa",
                        max_length=20,
                    ),
                ),
                (
                    "video_stato_gruppo_rientro",
                    models.FileField(
                        blank=True,
                        help_text="Video dello stato del gruppo al rientro",
                        null=True,
                        upload_to=automezzi.models.affidamento_gruppo_video_rientro_upload_path,
                    ),
                ),
                (
                    "data_rientro_effettivo",
                    models.DateField(
                        blank=True, help_text="Data effettiva di rientro", null=True
                    ),
                ),
                (
                    "carburante_rientro",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("vuoto", "Vuoto"),
                            ("1/4", "1/4"),
                            ("1/2", "1/2"),
                            ("3/4", "3/4"),
                            ("pieno", "Pieno"),
                        ],
                        help_text="Livello carburante al rientro",
                        max_length=10,
                    ),
                ),
                (
                    "note_rientro",
                    models.TextField(
                        blank=True, help_text="Note sul rientro e condizioni del gruppo"
                    ),
                ),
                (
                    "danni_riscontrati",
                    models.TextField(
                        blank=True, help_text="Eventuali danni riscontrati al rientro"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Dipendente a cui viene affidato il gruppo",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affidamenti_gruppo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "gruppo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affidamenti_gruppo",
                        to="automezzi.gruppo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Affidamento Gruppo",
                "verbose_name_plural": "Affidamenti Gruppi",
                "ordering": ["-data_inizio"],
            },
        ),
        migrations.CreateModel(
            name="ManutenzioneGruppo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_apertura",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e ora di apertura della manutenzione",
                        null=True,
                    ),
                ),
                (
                    "data_prevista",
                    models.DateField(
                        help_text="Data prevista per l'intervento di manutenzione",
                        null=True,
                    ),
                ),
                ("descrizione", models.CharField(max_length=255)),
                (
                    "stato",
                    models.CharField(
                        choices=[
                            ("aperta", "Manutenzione Aperta"),
                            ("in_corso", "In Corso"),
                            ("terminata", "Terminata"),
                        ],
                        default="aperta",
                        help_text="Stato della manutenzione",
                        max_length=10,
                    ),
                ),
                (
                    "luogo",
                    models.CharField(
                        blank=True,
                        help_text="Luogo dove viene eseguita la manutenzione",
                        max_length=200,
                    ),
                ),
                (
                    "costo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Costo della manutenzione (da compilare al termine)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "ore_lavoro",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Ore di funzionamento al momento della manutenzione",
                        null=True,
                    ),
                ),
                (
                    "data_inizio_manutenzione",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data e ora di inizio della manutenzione",
                        null=True,
                    ),
                ),
                (
                    "note_responsabile",
                    models.TextField(blank=True, help_text="Note del responsabile"),
                ),
                (
                    "data_completamento",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data e ora di completamento della manutenzione",
                        null=True,
                    ),
                ),
                (
                    "note_finali",
                    models.TextField(
                        blank=True, help_text="Note finali e dettagli del lavoro svolto"
                    ),
                ),
                ("cambio_olio", models.BooleanField(default=False)),
                ("cambio_filtro_aria", models.BooleanField(default=False)),
                ("cambio_filtro_carburante", models.BooleanField(default=False)),
                ("cambio_filtro_olio", models.BooleanField(default=False)),
                ("revisione_batteria", models.BooleanField(default=False)),
                ("prova_funzionamento", models.BooleanField(default=False)),
                (
                    "fornitore",
                    models.ForeignKey(
                        blank=True,
                        help_text="Fornitore/Officina che esegue la manutenzione",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="anagrafica.fornitore",
                    ),
                ),
                (
                    "gruppo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manutenzioni_gruppo",
                        to="automezzi.gruppo",
                    ),
                ),
                (
                    "responsabile",
                    models.ForeignKey(
                        blank=True,
                        help_text="Responsabile dell'esecuzione della manutenzione",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manutenzioni_gruppo_responsabile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seguito_da",
                    models.ForeignKey(
                        blank=True,
                        help_text="Utente che ha aperto e segue la pratica di manutenzione",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manutenzioni_gruppo_seguite",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Manutenzione Gruppo",
                "verbose_name_plural": "Manutenzioni Gruppi",
                "ordering": ["-data_apertura"],
            },
        ),
    ]
