# Generated by Django 5.1.4 on 2026-03-06 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automezzi", "0005_gruppo_eventogruppo_affidamentogruppo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventoautomezzo",
            name="gruppo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eventi",
                to="automezzi.gruppo",
            ),
        ),
        migrations.AddField(
            model_name="manutenzione",
            name="gruppo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manutenzioni",
                to="automezzi.gruppo",
            ),
        ),
        migrations.AddField(
            model_name="rifornimento",
            name="gruppo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rifornimenti",
                to="automezzi.gruppo",
            ),
        ),
        migrations.AlterField(
            model_name="eventoautomezzo",
            name="automezzo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eventi",
                to="automezzi.automezzo",
            ),
        ),
        migrations.AlterField(
            model_name="manutenzione",
            name="automezzo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manutenzioni",
                to="automezzi.automezzo",
            ),
        ),
        migrations.AlterField(
            model_name="rifornimento",
            name="automezzo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rifornimenti",
                to="automezzi.automezzo",
            ),
        ),
        migrations.AlterField(
            model_name="rifornimento",
            name="chilometri",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Chilometraggio al momento del rifornimento",
                null=True,
            ),
        ),
    ]
