# Generated by Django 5.1.4 on 2026-03-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automezzi", "0006_eventoautomezzo_gruppo_manutenzione_gruppo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="automezzo",
            name="mappa_danni",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Mappa completa dei danni del veicolo: [{'area': 'cofano_anteriore', 'x': 50, 'y': 30, 'tipo': 'graffio', 'note': '...', 'data': '2024-01-15', 'fonte': 'affidamento/evento'}]",
            ),
        ),
        migrations.AddField(
            model_name="eventoautomezzo",
            name="danni",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Mappa danni rilevati durante l'evento: [{'area': 'cofano_anteriore', 'x': 50, 'y': 30, 'tipo': 'graffio', 'note': '...'}]",
            ),
        ),
    ]
