# Generated by Django 5.1.4 on 2026-01-31 05:42

import django.core.validators
import django.db.models.deletion
import prodotti.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("anagrafica", "0002_alter_cliente_id_alter_fornitore_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_categoria",
                    models.CharField(
                        help_text="Nome della categoria di prodotti",
                        max_length=200,
                        unique=True,
                        verbose_name="Nome Categoria",
                    ),
                ),
                (
                    "icona",
                    models.ImageField(
                        blank=True,
                        help_text="Icona rappresentativa della categoria",
                        null=True,
                        upload_to=prodotti.models.upload_categoria_icon,
                        verbose_name="Icona",
                    ),
                ),
                (
                    "descrizione",
                    models.TextField(
                        blank=True,
                        help_text="Descrizione dettagliata della categoria",
                        verbose_name="Descrizione",
                    ),
                ),
                (
                    "attiva",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se la categoria è attiva",
                        verbose_name="Attiva",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creato il"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aggiornato il"),
                ),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorie",
                "ordering": ["nome_categoria"],
            },
        ),
        migrations.CreateModel(
            name="Prodotto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_prodotto",
                    models.CharField(
                        help_text="Nome commerciale del prodotto",
                        max_length=200,
                        verbose_name="Nome Prodotto",
                    ),
                ),
                (
                    "descrizione_breve",
                    models.CharField(
                        blank=True,
                        help_text="Descrizione breve per listini",
                        max_length=500,
                        verbose_name="Descrizione Breve",
                    ),
                ),
                (
                    "descrizione_completa",
                    models.TextField(
                        blank=True,
                        help_text="Descrizione dettagliata del prodotto",
                        verbose_name="Descrizione Completa",
                    ),
                ),
                (
                    "ean",
                    models.CharField(
                        blank=True,
                        help_text="Codice a barre EAN-13 (opzionale)",
                        max_length=13,
                        verbose_name="Codice EAN",
                    ),
                ),
                (
                    "codice_interno",
                    models.CharField(
                        blank=True,
                        help_text="Codice interno aziendale",
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Codice Interno",
                    ),
                ),
                (
                    "codice_fornitore",
                    models.CharField(
                        blank=True,
                        help_text="Codice utilizzato dal fornitore",
                        max_length=50,
                        verbose_name="Codice Fornitore",
                    ),
                ),
                (
                    "qrcode_data",
                    models.CharField(
                        blank=True,
                        help_text="Contenuto del QR code (generato automaticamente o importato)",
                        max_length=500,
                        verbose_name="Dati QR Code",
                    ),
                ),
                (
                    "qrcode_image",
                    models.ImageField(
                        blank=True,
                        help_text="Immagine QR code (generata o importata)",
                        null=True,
                        upload_to=prodotti.models.upload_qrcode_image,
                        verbose_name="Immagine QR Code",
                    ),
                ),
                (
                    "barcode_data",
                    models.CharField(
                        blank=True,
                        help_text="Contenuto del barcode (EAN o personalizzato)",
                        max_length=100,
                        verbose_name="Dati Barcode",
                    ),
                ),
                (
                    "barcode_image",
                    models.ImageField(
                        blank=True,
                        help_text="Immagine barcode (generata o importata)",
                        null=True,
                        upload_to=prodotti.models.upload_barcode_image,
                        verbose_name="Immagine Barcode",
                    ),
                ),
                (
                    "tipo_prodotto",
                    models.CharField(
                        choices=[
                            ("fisico", "Prodotto fisico"),
                            ("servizio", "Servizio"),
                            ("digitale", "Prodotto digitale"),
                        ],
                        default="fisico",
                        max_length=10,
                        verbose_name="Tipo Prodotto",
                    ),
                ),
                (
                    "misura",
                    models.CharField(
                        choices=[
                            ("bottiglia", "Vendita a bottiglia"),
                            ("kilo", "Vendita al peso (kg)"),
                            ("litro", "Vendita al litro"),
                            ("confezione", "Vendita a confezione"),
                            ("pezzo", "Vendita a pezzo"),
                            ("metro", "Vendita al metro"),
                            ("mq", "Vendita a metro quadro"),
                        ],
                        default="pezzo",
                        max_length=15,
                        verbose_name="Unità di Misura",
                    ),
                ),
                (
                    "peso_netto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                        verbose_name="Peso Netto (kg)",
                    ),
                ),
                (
                    "peso_lordo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                        verbose_name="Peso Lordo (kg)",
                    ),
                ),
                (
                    "volume",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                        verbose_name="Volume (litri)",
                    ),
                ),
                (
                    "dimensioni",
                    models.CharField(
                        blank=True,
                        help_text="Es: 10x5x3 cm",
                        max_length=100,
                        verbose_name="Dimensioni",
                    ),
                ),
                (
                    "aliquota_iva",
                    models.CharField(
                        choices=[("4", "IVA 4%"), ("10", "IVA 10%"), ("22", "IVA 22%")],
                        default="22",
                        max_length=3,
                        verbose_name="Aliquota IVA",
                    ),
                ),
                ("attivo", models.BooleanField(default=True, verbose_name="Attivo")),
                ("novita", models.BooleanField(default=False, verbose_name="Novità")),
                (
                    "in_evidenza",
                    models.BooleanField(default=False, verbose_name="In Evidenza"),
                ),
                (
                    "immagine",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=prodotti.models.upload_prodotto_image,
                        verbose_name="Immagine",
                    ),
                ),
                (
                    "note_interne",
                    models.TextField(
                        blank=True,
                        help_text="Note visibili solo internamente",
                        verbose_name="Note Interne",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creato il"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aggiornato il"),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prodotti",
                        to="prodotti.categoria",
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "fornitore_principale",
                    models.ForeignKey(
                        blank=True,
                        help_text="Fornitore principale del prodotto (opzionale per prodotti multi-fornitore)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prodotti",
                        to="anagrafica.fornitore",
                        verbose_name="Fornitore Principale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prodotto",
                "verbose_name_plural": "Prodotti",
                "ordering": ["nome_prodotto"],
                "indexes": [
                    models.Index(fields=["ean"], name="prodotti_pr_ean_89ab0b_idx"),
                    models.Index(
                        fields=["codice_interno"], name="prodotti_pr_codice__7de774_idx"
                    ),
                    models.Index(
                        fields=["categoria", "attivo"],
                        name="prodotti_pr_categor_254d16_idx",
                    ),
                    models.Index(
                        fields=["attivo", "nome_prodotto"],
                        name="prodotti_pr_attivo_a36b65_idx",
                    ),
                    models.Index(
                        fields=["fornitore_principale"],
                        name="prodotti_pr_fornito_0da30a_idx",
                    ),
                ],
            },
        ),
    ]
