# Generated by Django 5.1.4 on 2026-02-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prodotti", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="prodotto",
            name="merce_deperibile",
            field=models.BooleanField(
                default=False,
                help_text="Indica se il prodotto è deperibile",
                verbose_name="Merce Deperibile",
            ),
        ),
    ]
