# Generated by Django 6.0.1 on 2026-01-17 11:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Collo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantita", models.IntegerField(default=1, verbose_name="Quantità")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("SCATOLA", "Scatola"),
                            ("PALLET", "Pallet"),
                            ("BUSTA", "Busta"),
                            ("CILINDRO", "Cilindro/Tubo"),
                            ("CASSA", "Cassa di legno"),
                            ("SACCO", "Sacco"),
                            ("ALTRO", "Altro"),
                        ],
                        default="SCATOLA",
                        max_length=20,
                        verbose_name="Tipo Imballaggio",
                    ),
                ),
                (
                    "lunghezza_cm",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Lunghezza (cm)"
                    ),
                ),
                (
                    "larghezza_cm",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Larghezza (cm)"
                    ),
                ),
                (
                    "altezza_cm",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Altezza (cm)"
                    ),
                ),
                (
                    "peso_kg",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Peso (kg)"
                    ),
                ),
                (
                    "volume_m3",
                    models.DecimalField(
                        decimal_places=4,
                        editable=False,
                        max_digits=8,
                        verbose_name="Volume (m³)",
                    ),
                ),
                (
                    "descrizione",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Descrizione Contenuto"
                    ),
                ),
                ("fragile", models.BooleanField(default=False, verbose_name="Fragile")),
                (
                    "stackable",
                    models.BooleanField(default=True, verbose_name="Impilabile"),
                ),
                ("ordine", models.IntegerField(default=0, verbose_name="Ordine")),
            ],
            options={
                "verbose_name": "Collo",
                "verbose_name_plural": "Colli",
                "ordering": ["ordine", "id"],
            },
        ),
        migrations.CreateModel(
            name="ConfigurazioneAPITrasporto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("BRT", "BRT"),
                            ("GLS", "GLS"),
                            ("DHL", "DHL Express"),
                            ("UPS", "UPS"),
                            ("FEDEX", "FedEx"),
                            ("TNT", "TNT"),
                            ("TIMOCOM", "TimoCom"),
                            ("TRANSEU", "Trans.eu"),
                            ("WTRANSNET", "Wtransnet"),
                            ("GOOGLE_MAPS", "Google Maps API"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Provider",
                    ),
                ),
                ("api_key", models.CharField(max_length=500, verbose_name="API Key")),
                (
                    "api_secret",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="API Secret"
                    ),
                ),
                ("api_endpoint", models.URLField(verbose_name="API Endpoint")),
                ("attivo", models.BooleanField(default=True, verbose_name="Attivo")),
                (
                    "configurazione_extra",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Configurazione Extra"
                    ),
                ),
                (
                    "ultimo_test",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ultimo Test"
                    ),
                ),
                (
                    "ultimo_test_successo",
                    models.BooleanField(
                        default=False, verbose_name="Ultimo Test Successo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Configurazione API Trasporto",
                "verbose_name_plural": "Configurazioni API Trasporto",
            },
        ),
        migrations.CreateModel(
            name="EventoTracking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo_evento",
                    models.CharField(
                        choices=[
                            ("RICHIESTA_INVIATA", "Richiesta Inviata"),
                            ("OFFERTA_RICEVUTA", "Offerta Ricevuta"),
                            ("OFFERTA_ACCETTATA", "Offerta Accettata"),
                            ("IN_CARICAMENTO", "In Caricamento"),
                            ("RITIRATO", "Ritirato"),
                            ("IN_TRANSITO", "In Transito"),
                            ("IN_CONSEGNA", "In Consegna"),
                            ("CONSEGNATO", "Consegnato"),
                            ("PROBLEMI", "Problemi/Ritardo"),
                            ("ANNULLATO", "Annullato"),
                        ],
                        max_length=50,
                        verbose_name="Tipo Evento",
                    ),
                ),
                (
                    "data_evento",
                    models.DateTimeField(auto_now_add=True, verbose_name="Data Evento"),
                ),
                (
                    "localita",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Località"
                    ),
                ),
                ("nota", models.TextField(blank=True, verbose_name="Nota")),
                (
                    "source_api",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Source API"
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="External ID"
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento Tracking",
                "verbose_name_plural": "Eventi Tracking",
                "ordering": ["-data_evento"],
            },
        ),
        migrations.CreateModel(
            name="OffertaTrasporto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "numero_offerta",
                    models.CharField(
                        blank=True,
                        help_text="Numero assegnato dal trasportatore",
                        max_length=100,
                        verbose_name="Numero Offerta",
                    ),
                ),
                (
                    "importo_trasporto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Importo Trasporto",
                    ),
                ),
                (
                    "importo_assicurazione",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Importo Assicurazione",
                    ),
                ),
                (
                    "importo_pedaggi",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Importo Pedaggi",
                    ),
                ),
                (
                    "importo_extra",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Importo Extra",
                    ),
                ),
                (
                    "descrizione_extra",
                    models.TextField(blank=True, verbose_name="Descrizione Extra"),
                ),
                (
                    "importo_totale",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Importo Totale"
                    ),
                ),
                (
                    "valuta",
                    models.CharField(
                        default="EUR", max_length=3, verbose_name="Valuta"
                    ),
                ),
                (
                    "prezzo_per_km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Prezzo per km",
                    ),
                ),
                (
                    "prezzo_per_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Prezzo per kg",
                    ),
                ),
                (
                    "data_ritiro_proposta",
                    models.DateField(verbose_name="Data Ritiro Proposta"),
                ),
                (
                    "ora_ritiro_dalle",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Ora Ritiro Dalle"
                    ),
                ),
                (
                    "ora_ritiro_alle",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Ora Ritiro Alle"
                    ),
                ),
                (
                    "data_consegna_prevista",
                    models.DateField(verbose_name="Data Consegna Prevista"),
                ),
                (
                    "ora_consegna_dalle",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Ora Consegna Dalle"
                    ),
                ),
                (
                    "ora_consegna_alle",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Ora Consegna Alle"
                    ),
                ),
                (
                    "tempo_transito_giorni",
                    models.IntegerField(verbose_name="Tempo Transito (giorni)"),
                ),
                (
                    "tipo_mezzo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FURGONE", "Furgone"),
                            ("CAMION_CENTINATO", "Camion Centinato"),
                            ("CAMION_FRIGO", "Camion Frigo"),
                            ("CAMION_SPONDA", "Camion con Sponda"),
                            ("CAMION_PIANALE", "Camion Pianale"),
                            ("BILICO", "Bilico/Articolato"),
                            ("ALTRO", "Altro"),
                        ],
                        max_length=30,
                        verbose_name="Tipo Mezzo",
                    ),
                ),
                (
                    "targa_mezzo",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Targa Mezzo"
                    ),
                ),
                (
                    "capienza_kg",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Capienza (kg)"
                    ),
                ),
                (
                    "capienza_m3",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Capienza (m³)"
                    ),
                ),
                (
                    "conducente_nome",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nome Conducente"
                    ),
                ),
                (
                    "conducente_telefono",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Telefono Conducente"
                    ),
                ),
                (
                    "termini_pagamento",
                    models.CharField(
                        blank=True,
                        help_text="Es: 30gg DFFM",
                        max_length=200,
                        verbose_name="Termini Pagamento",
                    ),
                ),
                (
                    "validita_offerta_giorni",
                    models.IntegerField(
                        default=7, verbose_name="Validità Offerta (giorni)"
                    ),
                ),
                (
                    "tracking_incluso",
                    models.BooleanField(default=False, verbose_name="Tracking Incluso"),
                ),
                (
                    "assicurazione_inclusa",
                    models.BooleanField(
                        default=False, verbose_name="Assicurazione Inclusa"
                    ),
                ),
                (
                    "scarico_a_piano_incluso",
                    models.BooleanField(
                        default=False, verbose_name="Scarico a Piano Incluso"
                    ),
                ),
                (
                    "numero_tracking",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Numero Tracking"
                    ),
                ),
                (
                    "link_tracking",
                    models.URLField(blank=True, verbose_name="Link Tracking"),
                ),
                (
                    "file_offerta",
                    models.FileField(
                        blank=True,
                        upload_to="trasporti/offerte/",
                        verbose_name="File Offerta",
                    ),
                ),
                (
                    "note_tecniche",
                    models.TextField(blank=True, verbose_name="Note Tecniche"),
                ),
                (
                    "note_commerciali",
                    models.TextField(blank=True, verbose_name="Note Commerciali"),
                ),
                (
                    "data_ricevimento",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data Ricevimento"
                    ),
                ),
                (
                    "data_scadenza_offerta",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Scadenza Offerta"
                    ),
                ),
                (
                    "confermata",
                    models.BooleanField(default=False, verbose_name="Confermata"),
                ),
                (
                    "data_conferma",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data Conferma"
                    ),
                ),
                (
                    "numero_ordine",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Numero Ordine"
                    ),
                ),
            ],
            options={
                "verbose_name": "Offerta Trasporto",
                "verbose_name_plural": "Offerte Trasporto",
                "ordering": ["importo_totale"],
            },
        ),
        migrations.CreateModel(
            name="ParametroValutazione",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "descrizione",
                    models.CharField(
                        help_text="Es: Affidabilità, Recensioni, Esperienza",
                        max_length=200,
                        verbose_name="Descrizione",
                    ),
                ),
                ("valore", models.CharField(max_length=200, verbose_name="Valore")),
                ("ordine", models.IntegerField(default=0, verbose_name="Ordine")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creato il"),
                ),
            ],
            options={
                "verbose_name": "Parametro Valutazione",
                "verbose_name_plural": "Parametri Valutazione",
                "ordering": ["ordine"],
            },
        ),
        migrations.CreateModel(
            name="RichiestaTrasporto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "numero",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("titolo", models.CharField(max_length=200, verbose_name="Titolo")),
                (
                    "descrizione",
                    models.TextField(blank=True, verbose_name="Descrizione"),
                ),
                (
                    "tipo_trasporto",
                    models.CharField(
                        choices=[
                            ("PACCO", "Pacco/Colli (Corriere Express)"),
                            ("LTL", "Carico Parziale (LTL - Groupage)"),
                            ("FTL", "Camion Completo (FTL - Dedicato)"),
                            ("SPECIALE", "Trasporto Speciale"),
                        ],
                        max_length=20,
                        verbose_name="Tipo Trasporto",
                    ),
                ),
                (
                    "stato",
                    models.CharField(
                        choices=[
                            ("BOZZA", "Bozza"),
                            ("RICHIESTA_INVIATA", "Richiesta Inviata"),
                            ("OFFERTE_RICEVUTE", "Offerte Ricevute"),
                            ("IN_VALUTAZIONE", "In Valutazione"),
                            ("APPROVATA", "Approvata"),
                            ("CONFERMATA", "Confermata"),
                            ("IN_CORSO", "Trasporto in Corso"),
                            ("CONSEGNATO", "Consegnato"),
                            ("ANNULLATA", "Annullata"),
                        ],
                        default="BOZZA",
                        max_length=30,
                        verbose_name="Stato",
                    ),
                ),
                (
                    "priorita",
                    models.CharField(
                        choices=[
                            ("BASSA", "Bassa"),
                            ("NORMALE", "Normale"),
                            ("ALTA", "Alta"),
                            ("URGENTE", "Urgente"),
                        ],
                        default="NORMALE",
                        max_length=10,
                        verbose_name="Priorità",
                    ),
                ),
                ("indirizzo_ritiro", models.TextField(verbose_name="Indirizzo Ritiro")),
                (
                    "cap_ritiro",
                    models.CharField(max_length=10, verbose_name="CAP Ritiro"),
                ),
                (
                    "citta_ritiro",
                    models.CharField(max_length=100, verbose_name="Città Ritiro"),
                ),
                (
                    "provincia_ritiro",
                    models.CharField(max_length=2, verbose_name="Provincia Ritiro"),
                ),
                (
                    "nazione_ritiro",
                    models.CharField(
                        default="IT", max_length=2, verbose_name="Nazione Ritiro"
                    ),
                ),
                (
                    "indirizzo_consegna",
                    models.TextField(verbose_name="Indirizzo Consegna"),
                ),
                (
                    "cap_consegna",
                    models.CharField(max_length=10, verbose_name="CAP Consegna"),
                ),
                (
                    "citta_consegna",
                    models.CharField(max_length=100, verbose_name="Città Consegna"),
                ),
                (
                    "provincia_consegna",
                    models.CharField(max_length=2, verbose_name="Provincia Consegna"),
                ),
                (
                    "nazione_consegna",
                    models.CharField(
                        default="IT", max_length=2, verbose_name="Nazione Consegna"
                    ),
                ),
                (
                    "lat_ritiro",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="Latitudine Ritiro",
                    ),
                ),
                (
                    "lon_ritiro",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="Longitudine Ritiro",
                    ),
                ),
                (
                    "lat_consegna",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="Latitudine Consegna",
                    ),
                ),
                (
                    "lon_consegna",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="Longitudine Consegna",
                    ),
                ),
                (
                    "distanza_km",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Distanza (km)"
                    ),
                ),
                (
                    "data_ritiro_richiesta",
                    models.DateField(verbose_name="Data Ritiro Richiesta"),
                ),
                (
                    "ora_ritiro_dalle",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Ora Ritiro Dalle"
                    ),
                ),
                (
                    "ora_ritiro_alle",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Ora Ritiro Alle"
                    ),
                ),
                (
                    "data_consegna_richiesta",
                    models.DateField(verbose_name="Data Consegna Richiesta"),
                ),
                (
                    "ora_consegna_dalle",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Ora Consegna Dalle"
                    ),
                ),
                (
                    "ora_consegna_alle",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Ora Consegna Alle"
                    ),
                ),
                (
                    "tipo_merce",
                    models.CharField(
                        help_text="Es: Mobili, Elettronica, Alimentari, etc.",
                        max_length=200,
                        verbose_name="Tipo Merce",
                    ),
                ),
                (
                    "valore_merce",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Valore Merce",
                    ),
                ),
                (
                    "valuta",
                    models.CharField(
                        default="EUR", max_length=3, verbose_name="Valuta"
                    ),
                ),
                (
                    "merce_fragile",
                    models.BooleanField(default=False, verbose_name="Merce Fragile"),
                ),
                (
                    "merce_deperibile",
                    models.BooleanField(default=False, verbose_name="Merce Deperibile"),
                ),
                (
                    "merce_pericolosa",
                    models.BooleanField(
                        default=False, verbose_name="Merce Pericolosa (ADR)"
                    ),
                ),
                (
                    "codice_adr",
                    models.CharField(
                        blank=True,
                        help_text="Es: UN1203 per benzina",
                        max_length=50,
                        verbose_name="Codice ADR",
                    ),
                ),
                (
                    "temperatura_controllata",
                    models.BooleanField(
                        default=False, verbose_name="Temperatura Controllata"
                    ),
                ),
                (
                    "temperatura_min",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Temperatura Min (°C)"
                    ),
                ),
                (
                    "temperatura_max",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Temperatura Max (°C)"
                    ),
                ),
                (
                    "assicurazione_richiesta",
                    models.BooleanField(
                        default=False, verbose_name="Assicurazione Richiesta"
                    ),
                ),
                (
                    "massimale_assicurazione",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Massimale Assicurazione",
                    ),
                ),
                (
                    "scarico_a_piano",
                    models.BooleanField(default=False, verbose_name="Scarico a Piano"),
                ),
                (
                    "numero_piano",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Numero Piano"
                    ),
                ),
                (
                    "presenza_montacarichi",
                    models.BooleanField(
                        default=False, verbose_name="Presenza Montacarichi"
                    ),
                ),
                (
                    "tracking_richiesto",
                    models.BooleanField(
                        default=True, verbose_name="Tracking Richiesto"
                    ),
                ),
                (
                    "packing_list_richiesto",
                    models.BooleanField(
                        default=False, verbose_name="Packing List Richiesto"
                    ),
                ),
                (
                    "budget_massimo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Budget Massimo",
                    ),
                ),
                (
                    "data_creazione",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data Creazione"
                    ),
                ),
                (
                    "data_invio_richiesta",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data Invio Richiesta"
                    ),
                ),
                (
                    "data_valutazione",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data Valutazione"
                    ),
                ),
                (
                    "data_approvazione",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data Approvazione"
                    ),
                ),
                (
                    "data_conferma",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data Conferma"
                    ),
                ),
                (
                    "data_ritiro_effettivo",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data Ritiro Effettivo"
                    ),
                ),
                (
                    "data_consegna_effettiva",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data Consegna Effettiva"
                    ),
                ),
                (
                    "note_interne",
                    models.TextField(blank=True, verbose_name="Note Interne"),
                ),
                (
                    "note_ritiro",
                    models.TextField(
                        blank=True,
                        help_text="Es: Suonare al citofono Rossi, accesso dal retro",
                        verbose_name="Note Ritiro",
                    ),
                ),
                (
                    "note_consegna",
                    models.TextField(
                        blank=True,
                        help_text="Es: Chiamare prima della consegna",
                        verbose_name="Note Consegna",
                    ),
                ),
            ],
            options={
                "verbose_name": "Richiesta Trasporto",
                "verbose_name_plural": "Richieste Trasporto",
                "ordering": ["-data_creazione"],
            },
        ),
        migrations.CreateModel(
            name="TrasportatoreOfferta",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email_inviata",
                    models.BooleanField(default=False, verbose_name="Email Inviata"),
                ),
                (
                    "data_invio",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data Invio"
                    ),
                ),
                (
                    "email_letta",
                    models.BooleanField(default=False, verbose_name="Email Letta"),
                ),
                (
                    "data_lettura",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data Lettura"
                    ),
                ),
                (
                    "ha_risposto",
                    models.BooleanField(default=False, verbose_name="Ha Risposto"),
                ),
                (
                    "data_risposta",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data Risposta"
                    ),
                ),
                (
                    "numero_solleciti",
                    models.IntegerField(default=0, verbose_name="Numero Solleciti"),
                ),
                (
                    "data_ultimo_sollecito",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data Ultimo Sollecito"
                    ),
                ),
                (
                    "token_accesso",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "note_trasportatore",
                    models.TextField(blank=True, verbose_name="Note Trasportatore"),
                ),
            ],
            options={
                "verbose_name": "Trasportatore Offerta",
                "verbose_name_plural": "Trasportatori Offerte",
            },
        ),
    ]
