# Generated by Django 6.0.1 on 2026-01-17 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("anagrafica", "0001_initial"),
        ("trasporti", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="offertatrasporto",
            name="operatore_inserimento",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Operatore Inserimento",
            ),
        ),
        migrations.AddField(
            model_name="offertatrasporto",
            name="trasportatore",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="anagrafica.fornitore",
                verbose_name="Trasportatore",
            ),
        ),
        migrations.AddField(
            model_name="eventotracking",
            name="offerta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eventi_tracking",
                to="trasporti.offertatrasporto",
                verbose_name="Offerta",
            ),
        ),
        migrations.AddField(
            model_name="parametrovalutazione",
            name="creato_da",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parametri_trasporti",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creato Da",
            ),
        ),
        migrations.AddField(
            model_name="parametrovalutazione",
            name="offerta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parametri",
                to="trasporti.offertatrasporto",
                verbose_name="Offerta",
            ),
        ),
        migrations.AddField(
            model_name="richiestatrasporto",
            name="approvatore",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trasporti_approvati",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approvatore",
            ),
        ),
        migrations.AddField(
            model_name="richiestatrasporto",
            name="offerta_approvata",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="trasporti.offertatrasporto",
                verbose_name="Offerta Approvata",
            ),
        ),
        migrations.AddField(
            model_name="richiestatrasporto",
            name="operatore",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trasporti_gestiti",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Operatore",
            ),
        ),
        migrations.AddField(
            model_name="richiestatrasporto",
            name="richiedente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="trasporti_richiesti",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Richiedente",
            ),
        ),
        migrations.AddField(
            model_name="offertatrasporto",
            name="richiesta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offerte",
                to="trasporti.richiestatrasporto",
                verbose_name="Richiesta",
            ),
        ),
        migrations.AddField(
            model_name="collo",
            name="richiesta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="colli",
                to="trasporti.richiestatrasporto",
                verbose_name="Richiesta",
            ),
        ),
        migrations.AddField(
            model_name="trasportatoreofferta",
            name="richiesta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="trasporti.richiestatrasporto",
                verbose_name="Richiesta",
            ),
        ),
        migrations.AddField(
            model_name="trasportatoreofferta",
            name="trasportatore",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="anagrafica.fornitore",
                verbose_name="Trasportatore",
            ),
        ),
        migrations.AddField(
            model_name="richiestatrasporto",
            name="trasportatori",
            field=models.ManyToManyField(
                blank=True,
                through="trasporti.TrasportatoreOfferta",
                to="anagrafica.fornitore",
                verbose_name="Trasportatori",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="offertatrasporto",
            unique_together={("richiesta", "trasportatore")},
        ),
        migrations.AlterUniqueTogether(
            name="trasportatoreofferta",
            unique_together={("richiesta", "trasportatore")},
        ),
    ]
