# Generated by Django 4.2.21 on 2025-10-01 14:31

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("anagrafica", "0002_rappresentante_stabilimenti_competenza"),
        ("prodotti", "0001_initial"),
        ("ricezioni", "0001_initial"),
        ("acquisti", "0003_alter_ordineacquisto_fornitore_email_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RiconoscimentoFornitore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_riconoscimento",
                    models.CharField(
                        help_text="Numero riconoscimento generato automaticamente",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("data_creazione", models.DateTimeField(auto_now_add=True)),
                ("periodo_da", models.DateField(help_text="Data inizio periodo")),
                ("periodo_a", models.DateField(help_text="Data fine periodo")),
                (
                    "stato",
                    models.CharField(
                        choices=[
                            ("bozza", "Bozza"),
                            ("definitivo", "Definitivo"),
                            ("inviato", "Inviato al Fornitore"),
                            ("confermato", "Confermato dal Fornitore"),
                            ("fatturato", "Fatturato"),
                            ("annullato", "Annullato"),
                        ],
                        default="bozza",
                        max_length=20,
                    ),
                ),
                (
                    "include_ordini_ricevuti",
                    models.BooleanField(
                        default=True, help_text="Include ordini già ricevuti"
                    ),
                ),
                (
                    "include_ordini_da_ricevere",
                    models.BooleanField(
                        default=False, help_text="Include ordini ancora da ricevere"
                    ),
                ),
                (
                    "include_ricezioni_manuali",
                    models.BooleanField(
                        default=True,
                        help_text="Include ricezioni manuali (senza ordine)",
                    ),
                ),
                (
                    "totale_imponibile",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Totale imponibile",
                        max_digits=12,
                    ),
                ),
                (
                    "totale_iva",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Totale IVA",
                        max_digits=12,
                    ),
                ),
                (
                    "totale_riconoscimento",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Totale compreso IVA",
                        max_digits=12,
                    ),
                ),
                ("data_conferma", models.DateTimeField(blank=True, null=True)),
                (
                    "inviato_via_email",
                    models.BooleanField(default=False, help_text="Inviato via email"),
                ),
                ("data_invio_email", models.DateTimeField(blank=True, null=True)),
                (
                    "email_destinatario",
                    models.EmailField(
                        blank=True, help_text="Email di invio", max_length=254
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, help_text="Note sul riconoscimento"),
                ),
                ("data_modifica", models.DateTimeField(auto_now=True)),
                (
                    "confermato_da",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="riconoscimenti_confermati",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creato_da",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="riconoscimenti_creati",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fornitore",
                    models.ForeignKey(
                        help_text="Fornitore del riconoscimento",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="anagrafica.fornitore",
                    ),
                ),
            ],
            options={
                "verbose_name": "Riconoscimento Fornitore",
                "verbose_name_plural": "Riconoscimenti Fornitori",
                "ordering": ["-data_creazione"],
            },
        ),
        migrations.CreateModel(
            name="ExportRiconoscimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_export",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("excel", "Excel"), ("csv", "CSV")],
                        max_length=10,
                    ),
                ),
                (
                    "nome_file",
                    models.CharField(help_text="Nome file generato", max_length=255),
                ),
                (
                    "file_path",
                    models.CharField(
                        help_text="Percorso file sul server", max_length=500
                    ),
                ),
                ("inviato_via_email", models.BooleanField(default=False)),
                ("email_destinatario", models.EmailField(blank=True, max_length=254)),
                ("data_export", models.DateTimeField(auto_now_add=True)),
                (
                    "esportato_da",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "riconoscimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export",
                        to="fatturazionepassiva.riconoscimentofornitore",
                    ),
                ),
            ],
            options={
                "verbose_name": "Export Riconoscimento",
                "verbose_name_plural": "Export Riconoscimenti",
                "ordering": ["-data_export"],
            },
        ),
        migrations.CreateModel(
            name="RigaRiconoscimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_origine",
                    models.CharField(
                        choices=[
                            ("ordine_ricevuto", "Da Ordine Ricevuto"),
                            ("ordine_da_ricevere", "Da Ordine da Ricevere"),
                            ("ricezione_manuale", "Da Ricezione Manuale"),
                            ("manuale", "Inserimento Manuale"),
                        ],
                        help_text="Origine del dato",
                        max_length=20,
                    ),
                ),
                (
                    "quantita_ordinata",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Quantità ordinata (se da ordine)",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "quantita_riconosciuta",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Quantità da riconoscere/fatturare",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "prezzo_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Prezzo unitario senza IVA",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "aliquota_iva",
                    models.DecimalField(
                        decimal_places=2,
                        default=22.0,
                        help_text="Aliquota IVA in percentuale",
                        max_digits=5,
                    ),
                ),
                (
                    "descrizione",
                    models.CharField(
                        help_text="Descrizione della riga", max_length=255
                    ),
                ),
                ("note", models.TextField(blank=True, help_text="Note aggiuntive")),
                ("data_creazione", models.DateTimeField(auto_now_add=True)),
                ("data_modifica", models.DateTimeField(auto_now=True)),
                (
                    "ordine_riferimento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="acquisti.ordineacquisto",
                    ),
                ),
                (
                    "prodotto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="prodotti.prodotto",
                    ),
                ),
                (
                    "ricezione_riferimento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ricezioni.ricezione",
                    ),
                ),
                (
                    "riconoscimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="righe",
                        to="fatturazionepassiva.riconoscimentofornitore",
                    ),
                ),
                (
                    "riga_ordine_riferimento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="acquisti.rigaordine",
                    ),
                ),
                (
                    "riga_ricezione_riferimento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ricezioni.rigaricezione",
                    ),
                ),
            ],
            options={
                "verbose_name": "Riga Riconoscimento",
                "verbose_name_plural": "Righe Riconoscimento",
                "ordering": ["riconoscimento", "prodotto"],
                "indexes": [
                    models.Index(
                        fields=["riconoscimento"], name="fatturazion_riconos_c2be28_idx"
                    ),
                    models.Index(
                        fields=["prodotto"], name="fatturazion_prodott_2b278e_idx"
                    ),
                    models.Index(
                        fields=["tipo_origine"], name="fatturazion_tipo_or_666d8d_idx"
                    ),
                    models.Index(
                        fields=["ordine_riferimento"],
                        name="fatturazion_ordine__f7b118_idx",
                    ),
                    models.Index(
                        fields=["ricezione_riferimento"],
                        name="fatturazion_ricezio_e8c4a8_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="riconoscimentofornitore",
            index=models.Index(
                fields=["numero_riconoscimento"], name="fatturazion_numero__bba370_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="riconoscimentofornitore",
            index=models.Index(
                fields=["fornitore"], name="fatturazion_fornito_7c6190_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="riconoscimentofornitore",
            index=models.Index(
                fields=["periodo_da", "periodo_a"],
                name="fatturazion_periodo_ed2125_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="riconoscimentofornitore",
            index=models.Index(fields=["stato"], name="fatturazion_stato_2d9924_idx"),
        ),
        migrations.AddIndex(
            model_name="riconoscimentofornitore",
            index=models.Index(
                fields=["data_creazione"], name="fatturazion_data_cr_c4cbb7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="riconoscimentofornitore",
            unique_together={("fornitore", "periodo_da", "periodo_a")},
        ),
    ]
