# Generated by Django 6.0.1 on 2026-01-19 04:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("anagrafica", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FornitorePreventivo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email_inviata",
                    models.BooleanField(default=False, verbose_name="Email Inviata"),
                ),
                (
                    "data_invio",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data Invio"
                    ),
                ),
                (
                    "email_letta",
                    models.BooleanField(default=False, verbose_name="Email Letta"),
                ),
                (
                    "data_lettura",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data Lettura"
                    ),
                ),
                (
                    "ha_risposto",
                    models.BooleanField(default=False, verbose_name="Ha Risposto"),
                ),
                (
                    "data_risposta",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data Risposta"
                    ),
                ),
                (
                    "numero_solleciti",
                    models.IntegerField(default=0, verbose_name="Numero Solleciti"),
                ),
                (
                    "data_ultimo_sollecito",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data Ultimo Sollecito"
                    ),
                ),
                (
                    "token_accesso",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "note_fornitore",
                    models.TextField(blank=True, verbose_name="Note Fornitore"),
                ),
                (
                    "fornitore",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="anagrafica.fornitore",
                        verbose_name="Fornitore",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fornitore Preventivo",
                "verbose_name_plural": "Fornitori Preventivi",
            },
        ),
        migrations.CreateModel(
            name="Offerta",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "numero_offerta",
                    models.CharField(
                        blank=True,
                        help_text="Numero assegnato dal fornitore",
                        max_length=100,
                        verbose_name="Numero Offerta",
                    ),
                ),
                (
                    "importo_merce",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Importo Merce/Servizi",
                    ),
                ),
                (
                    "importo_trasporto",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Importo Trasporto",
                    ),
                ),
                (
                    "importo_imballo",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Importo Imballo",
                    ),
                ),
                (
                    "importo_installazione",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Importo Installazione",
                    ),
                ),
                (
                    "importo_extra",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Importo Extra",
                    ),
                ),
                (
                    "descrizione_extra",
                    models.TextField(blank=True, verbose_name="Descrizione Extra"),
                ),
                (
                    "sconto_percentuale",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Sconto %",
                    ),
                ),
                (
                    "sconto_importo",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Sconto Importo",
                    ),
                ),
                (
                    "importo_totale",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Importo Totale"
                    ),
                ),
                (
                    "valuta",
                    models.CharField(
                        default="EUR", max_length=3, verbose_name="Valuta"
                    ),
                ),
                (
                    "tempo_consegna_giorni",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Tempo Consegna (giorni)"
                    ),
                ),
                (
                    "data_consegna_proposta",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Consegna Proposta"
                    ),
                ),
                (
                    "note_consegna",
                    models.TextField(blank=True, verbose_name="Note Consegna"),
                ),
                (
                    "termini_pagamento",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "-- Non specificato --"),
                            ("CONTANTI", "Contanti"),
                            ("30GG", "30 giorni"),
                            ("60GG", "60 giorni"),
                            ("90GG", "90 giorni"),
                            ("30GG_DFFM", "30 giorni DFFM"),
                            ("60GG_DFFM", "60 giorni DFFM"),
                            ("ANTICIPATO", "Pagamento anticipato"),
                        ],
                        max_length=50,
                        verbose_name="Termini Pagamento",
                    ),
                ),
                (
                    "validita_offerta_giorni",
                    models.IntegerField(
                        default=30, verbose_name="Validità Offerta (giorni)"
                    ),
                ),
                (
                    "garanzia_mesi",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Garanzia (mesi)"
                    ),
                ),
                (
                    "note_garanzia",
                    models.TextField(blank=True, verbose_name="Note Garanzia"),
                ),
                (
                    "trasporto_incluso",
                    models.BooleanField(
                        default=False, verbose_name="Trasporto Incluso"
                    ),
                ),
                (
                    "installazione_inclusa",
                    models.BooleanField(
                        default=False, verbose_name="Installazione Inclusa"
                    ),
                ),
                (
                    "formazione_inclusa",
                    models.BooleanField(
                        default=False, verbose_name="Formazione Inclusa"
                    ),
                ),
                (
                    "file_offerta",
                    models.FileField(
                        blank=True,
                        upload_to="preventivi_beni/offerte/",
                        verbose_name="File Offerta",
                    ),
                ),
                (
                    "note_tecniche",
                    models.TextField(blank=True, verbose_name="Note Tecniche"),
                ),
                (
                    "note_commerciali",
                    models.TextField(blank=True, verbose_name="Note Commerciali"),
                ),
                (
                    "data_ricevimento",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data Ricevimento"
                    ),
                ),
                (
                    "data_scadenza_offerta",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Scadenza Offerta"
                    ),
                ),
                (
                    "confermata",
                    models.BooleanField(default=False, verbose_name="Confermata"),
                ),
                (
                    "data_conferma",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data Conferma"
                    ),
                ),
                (
                    "numero_ordine",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Numero Ordine"
                    ),
                ),
                (
                    "fornitore",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="anagrafica.fornitore",
                        verbose_name="Fornitore",
                    ),
                ),
                (
                    "operatore_inserimento",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Operatore Inserimento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Offerta",
                "verbose_name_plural": "Offerte",
                "ordering": ["importo_totale"],
            },
        ),
        migrations.CreateModel(
            name="ParametroValutazione",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "descrizione",
                    models.CharField(
                        help_text="Es: Tempo consegna, Garanzia, Assistenza",
                        max_length=200,
                        verbose_name="Descrizione",
                    ),
                ),
                ("valore", models.CharField(max_length=200, verbose_name="Valore")),
                ("ordine", models.IntegerField(default=0, verbose_name="Ordine")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creato il"),
                ),
                (
                    "creato_da",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parametri_preventivi_beni",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creato Da",
                    ),
                ),
                (
                    "offerta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parametri",
                        to="preventivi_beni.offerta",
                        verbose_name="Offerta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parametro Valutazione",
                "verbose_name_plural": "Parametri Valutazione",
                "ordering": ["ordine"],
            },
        ),
        migrations.CreateModel(
            name="RichiestaPreventivo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "numero",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("titolo", models.CharField(max_length=200, verbose_name="Titolo")),
                (
                    "descrizione",
                    models.TextField(blank=True, verbose_name="Descrizione"),
                ),
                (
                    "tipo_richiesta",
                    models.CharField(
                        choices=[
                            ("BENI", "Beni/Materiali"),
                            ("SERVIZI", "Servizi"),
                            ("MISTO", "Beni e Servizi"),
                            ("MANUTENZIONE", "Manutenzione"),
                            ("CONSULENZA", "Consulenza"),
                        ],
                        default="BENI",
                        max_length=20,
                        verbose_name="Tipo Richiesta",
                    ),
                ),
                (
                    "stato",
                    models.CharField(
                        choices=[
                            ("BOZZA", "Bozza"),
                            ("RICHIESTA_INVIATA", "Richiesta Inviata"),
                            ("OFFERTE_RICEVUTE", "Offerte Ricevute"),
                            ("IN_VALUTAZIONE", "In Valutazione"),
                            ("APPROVATA", "Approvata"),
                            ("CONFERMATA", "Confermata"),
                            ("ORDINATO", "Ordine Emesso"),
                            ("ANNULLATA", "Annullata"),
                        ],
                        default="BOZZA",
                        max_length=30,
                        verbose_name="Stato",
                    ),
                ),
                (
                    "priorita",
                    models.CharField(
                        choices=[
                            ("BASSA", "Bassa"),
                            ("NORMALE", "Normale"),
                            ("ALTA", "Alta"),
                            ("URGENTE", "Urgente"),
                        ],
                        default="NORMALE",
                        max_length=10,
                        verbose_name="Priorità",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MATERIALI", "Materiali da costruzione"),
                            ("FERRAMENTA", "Ferramenta"),
                            ("ELETTRICO", "Materiale elettrico"),
                            ("IDRAULICA", "Materiale idraulico"),
                            ("ATTREZZATURE", "Attrezzature e macchinari"),
                            ("UFFICIO", "Materiale ufficio"),
                            ("IT", "IT e informatica"),
                            ("SERVIZI_TECNICI", "Servizi tecnici"),
                            ("SERVIZI_PROF", "Servizi professionali"),
                            ("MANUTENZIONE", "Manutenzione"),
                            ("ALTRO", "Altro"),
                        ],
                        max_length=30,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "luogo_consegna",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Luogo Consegna/Esecuzione",
                    ),
                ),
                (
                    "indirizzo_consegna",
                    models.TextField(blank=True, verbose_name="Indirizzo Completo"),
                ),
                (
                    "data_consegna_richiesta",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Consegna Richiesta"
                    ),
                ),
                (
                    "data_scadenza_offerte",
                    models.DateField(
                        blank=True, null=True, verbose_name="Scadenza Ricezione Offerte"
                    ),
                ),
                (
                    "budget_massimo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Budget Massimo",
                    ),
                ),
                (
                    "valuta",
                    models.CharField(
                        default="EUR", max_length=3, verbose_name="Valuta"
                    ),
                ),
                (
                    "condizioni_pagamento_richieste",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "-- Non specificato --"),
                            ("CONTANTI", "Contanti"),
                            ("30GG", "30 giorni"),
                            ("60GG", "60 giorni"),
                            ("90GG", "90 giorni"),
                            ("30GG_DFFM", "30 giorni DFFM"),
                            ("60GG_DFFM", "60 giorni DFFM"),
                            ("ANTICIPATO", "Pagamento anticipato"),
                        ],
                        max_length=20,
                        verbose_name="Condizioni Pagamento Richieste",
                    ),
                ),
                (
                    "data_creazione",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data Creazione"
                    ),
                ),
                (
                    "data_invio_richiesta",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data Invio Richiesta"
                    ),
                ),
                (
                    "data_valutazione",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data Valutazione"
                    ),
                ),
                (
                    "data_approvazione",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data Approvazione"
                    ),
                ),
                (
                    "data_conferma",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data Conferma"
                    ),
                ),
                (
                    "note_interne",
                    models.TextField(blank=True, verbose_name="Note Interne"),
                ),
                (
                    "note_per_fornitori",
                    models.TextField(
                        blank=True,
                        help_text="Queste note saranno visibili ai fornitori nella richiesta",
                        verbose_name="Note per Fornitori",
                    ),
                ),
                (
                    "approvatore",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preventivi_beni_approvati",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approvatore",
                    ),
                ),
                (
                    "fornitori",
                    models.ManyToManyField(
                        blank=True,
                        through="preventivi_beni.FornitorePreventivo",
                        to="anagrafica.fornitore",
                        verbose_name="Fornitori",
                    ),
                ),
                (
                    "offerta_approvata",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="preventivi_beni.offerta",
                        verbose_name="Offerta Approvata",
                    ),
                ),
                (
                    "operatore",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preventivi_beni_gestiti",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Operatore",
                    ),
                ),
                (
                    "richiedente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="preventivi_beni_richiesti",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Richiedente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Richiesta Preventivo Beni",
                "verbose_name_plural": "Richieste Preventivi Beni",
                "ordering": ["-data_creazione"],
            },
        ),
        migrations.AddField(
            model_name="offerta",
            name="richiesta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offerte",
                to="preventivi_beni.richiestapreventivo",
                verbose_name="Richiesta",
            ),
        ),
        migrations.AddField(
            model_name="fornitorepreventivo",
            name="richiesta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="preventivi_beni.richiestapreventivo",
                verbose_name="Richiesta",
            ),
        ),
        migrations.CreateModel(
            name="VocePreventivo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "codice",
                    models.CharField(
                        blank=True,
                        help_text="Codice interno o riferimento",
                        max_length=50,
                        verbose_name="Codice Articolo",
                    ),
                ),
                ("descrizione", models.TextField(verbose_name="Descrizione")),
                (
                    "unita_misura",
                    models.CharField(
                        choices=[
                            ("PZ", "Pezzi"),
                            ("NR", "Numero"),
                            ("KG", "Kg"),
                            ("MT", "Metri"),
                            ("MQ", "Metri quadri"),
                            ("MC", "Metri cubi"),
                            ("LT", "Litri"),
                            ("H", "Ore"),
                            ("GG", "Giorni"),
                            ("CORPO", "A corpo"),
                            ("CONF", "Confezione"),
                            ("CF", "Cartone/Fardello"),
                            ("PL", "Pallet"),
                        ],
                        default="PZ",
                        max_length=10,
                        verbose_name="Unità di Misura",
                    ),
                ),
                (
                    "quantita",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Quantità"
                    ),
                ),
                (
                    "prezzo_unitario_stimato",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Prezzo Unitario Stimato",
                    ),
                ),
                (
                    "marca_richiesta",
                    models.CharField(
                        blank=True,
                        help_text="Marca preferita o equivalente",
                        max_length=100,
                        verbose_name="Marca Richiesta",
                    ),
                ),
                (
                    "modello_richiesto",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Modello Richiesto"
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Specifiche tecniche, requisiti particolari",
                        verbose_name="Note",
                    ),
                ),
                (
                    "obbligatoria",
                    models.BooleanField(
                        default=True,
                        help_text="Se deselezionato, il fornitore può omettere questa voce",
                        verbose_name="Voce Obbligatoria",
                    ),
                ),
                ("ordine", models.IntegerField(default=0, verbose_name="Ordine")),
                (
                    "richiesta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voci",
                        to="preventivi_beni.richiestapreventivo",
                        verbose_name="Richiesta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Voce Preventivo",
                "verbose_name_plural": "Voci Preventivo",
                "ordering": ["ordine", "id"],
            },
        ),
        migrations.CreateModel(
            name="VoceOfferta",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("descrizione", models.TextField(verbose_name="Descrizione")),
                (
                    "marca",
                    models.CharField(blank=True, max_length=100, verbose_name="Marca"),
                ),
                (
                    "modello",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Modello"
                    ),
                ),
                (
                    "codice_fornitore",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Codice Fornitore"
                    ),
                ),
                (
                    "quantita",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Quantità"
                    ),
                ),
                (
                    "unita_misura",
                    models.CharField(default="PZ", max_length=10, verbose_name="U.M."),
                ),
                (
                    "prezzo_unitario",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prezzo Unitario"
                    ),
                ),
                (
                    "sconto_riga",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Sconto %",
                    ),
                ),
                (
                    "importo_riga",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Importo Riga"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Note")),
                ("ordine", models.IntegerField(default=0, verbose_name="Ordine")),
                (
                    "offerta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voci",
                        to="preventivi_beni.offerta",
                        verbose_name="Offerta",
                    ),
                ),
                (
                    "voce_richiesta",
                    models.ForeignKey(
                        blank=True,
                        help_text="Collegamento alla voce originale della richiesta",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="preventivi_beni.vocepreventivo",
                        verbose_name="Voce Richiesta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Voce Offerta",
                "verbose_name_plural": "Voci Offerta",
                "ordering": ["ordine", "id"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="offerta",
            unique_together={("richiesta", "fornitore")},
        ),
        migrations.AlterUniqueTogether(
            name="fornitorepreventivo",
            unique_together={("richiesta", "fornitore")},
        ),
    ]
