# Generated by Django 6.0.1 on 2026-01-26 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automezzi', '0002_initial'),
        ('preventivi_beni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='richiestapreventivo',
            name='automezzo',
            field=models.ForeignKey(blank=True, help_text='Se selezionato, il libretto fronte verrà allegato alla richiesta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='richieste_preventivo', to='automezzi.automezzo', verbose_name='Automezzo'),
        ),
    ]
