# Generated by Django 6.0.1 on 2026-01-17 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payroll", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bustapaga",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buste_paga",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Dipendente",
            ),
        ),
        migrations.AddField(
            model_name="daticontrattualipayroll",
            name="ccnl",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="payroll.ccnl",
                verbose_name="CCNL Applicato",
            ),
        ),
        migrations.AddField(
            model_name="daticontrattualipayroll",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dati_payroll",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Dipendente",
            ),
        ),
        migrations.AddField(
            model_name="elementoretributivo",
            name="ccnl",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="elementi_retributivi",
                to="payroll.ccnl",
                verbose_name="CCNL",
            ),
        ),
        migrations.AddField(
            model_name="feriepermessipayroll",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ferie_permessi_payroll",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Dipendente",
            ),
        ),
        migrations.AddField(
            model_name="livelloinquadramento",
            name="ccnl",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="livelli",
                to="payroll.ccnl",
                verbose_name="CCNL",
            ),
        ),
        migrations.AddField(
            model_name="daticontrattualipayroll",
            name="livello",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="payroll.livelloinquadramento",
                verbose_name="Livello Inquadramento",
            ),
        ),
        migrations.AddField(
            model_name="manualepayroll",
            name="modificato_da",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manuali_modificati",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modificato Da",
            ),
        ),
        migrations.AddField(
            model_name="vocebustapaga",
            name="busta_paga",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="voci",
                to="payroll.bustapaga",
                verbose_name="Busta Paga",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bustapaga",
            unique_together={("user", "mese", "anno")},
        ),
        migrations.AlterUniqueTogether(
            name="elementoretributivo",
            unique_together={("ccnl", "codice")},
        ),
        migrations.AlterUniqueTogether(
            name="feriepermessipayroll",
            unique_together={("user", "anno", "tipo")},
        ),
        migrations.AlterUniqueTogether(
            name="livelloinquadramento",
            unique_together={("ccnl", "codice")},
        ),
    ]
