# Generated by Django 6.0.1 on 2026-01-23 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anagrafica', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('preventivi_beni', '0001_initial'),
        ('trasporti', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdineAcquisto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ordine', models.CharField(blank=True, help_text='Numero ODA generato automaticamente (ODA-YYYY-NNN)', max_length=50, unique=True)),
                ('data_ordine', models.DateTimeField(auto_now_add=True)),
                ('data_consegna_richiesta', models.DateField(help_text='Data richiesta per la consegna')),
                ('tipo_origine', models.CharField(choices=[('PREVENTIVO', 'Preventivo Beni/Servizi'), ('TRASPORTO', 'Trasporto'), ('MANUALE', 'Inserimento Manuale')], default='MANUALE', help_text="Tipo di documento che ha generato l'ordine", max_length=20)),
                ('object_id', models.CharField(blank=True, help_text="ID dell'oggetto collegato", max_length=50, null=True)),
                ('stato', models.CharField(choices=[('CREATO', 'Creato'), ('RICEVUTO', 'Ricevuto'), ('PAGATO', 'Pagato')], default='CREATO', help_text="Stato attuale dell'ordine", max_length=20)),
                ('importo_totale', models.DecimalField(decimal_places=2, help_text="Importo totale dell'ordine", max_digits=15)),
                ('valuta', models.CharField(default='EUR', max_length=3)),
                ('termini_pagamento', models.CharField(blank=True, help_text='Condizioni di pagamento', max_length=200)),
                ('tempi_consegna', models.CharField(blank=True, help_text='Tempi di consegna previsti', max_length=200)),
                ('oggetto_ordine', models.CharField(blank=True, help_text="Oggetto/descrizione dell'ordine", max_length=500)),
                ('descrizione_dettagliata', models.TextField(blank=True, help_text='Descrizione dettagliata dei beni/servizi')),
                ('data_ricevimento', models.DateTimeField(blank=True, help_text='Data di ricevimento della merce', null=True)),
                ('data_pagamento', models.DateTimeField(blank=True, help_text='Data di pagamento', null=True)),
                ('note_ordine', models.TextField(blank=True, help_text="Note generali sull'ordine")),
                ('riferimento_fornitore', models.CharField(blank=True, help_text='Riferimento/numero offerta del fornitore', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, help_text='Tipo di oggetto collegato (RichiestaPreventivo o RichiestaTrasporto)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('creato_da', models.ForeignKey(help_text="Utente che ha creato l'ordine", on_delete=django.db.models.deletion.PROTECT, related_name='ordini_acquisto_creati', to=settings.AUTH_USER_MODEL)),
                ('fornitore', models.ForeignKey(help_text="Fornitore dell'ordine", on_delete=django.db.models.deletion.PROTECT, related_name='ordini_acquisto', to='anagrafica.fornitore')),
                ('pagato_da', models.ForeignKey(blank=True, help_text='Utente che ha confermato il pagamento', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordini_acquisto_pagati', to=settings.AUTH_USER_MODEL)),
                ('ricevuto_da', models.ForeignKey(blank=True, help_text='Utente che ha confermato il ricevimento', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordini_acquisto_ricevuti', to=settings.AUTH_USER_MODEL)),
                ('richiesta_preventivo', models.ForeignKey(blank=True, help_text='Richiesta preventivo che ha generato questo ordine', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordini_acquisto', to='preventivi_beni.richiestapreventivo')),
                ('richiesta_trasporto', models.ForeignKey(blank=True, help_text='Richiesta trasporto che ha generato questo ordine', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordini_acquisto', to='trasporti.richiestatrasporto')),
            ],
            options={
                'verbose_name': 'Ordine di Acquisto',
                'verbose_name_plural': 'Ordini di Acquisto',
                'ordering': ['-data_ordine'],
                'indexes': [models.Index(fields=['numero_ordine'], name='acquisti_or_numero__795c3a_idx'), models.Index(fields=['stato'], name='acquisti_or_stato_12c5db_idx'), models.Index(fields=['fornitore'], name='acquisti_or_fornito_b17873_idx'), models.Index(fields=['data_ordine'], name='acquisti_or_data_or_241d7d_idx'), models.Index(fields=['tipo_origine'], name='acquisti_or_tipo_or_e44255_idx')],
            },
        ),
    ]
