# Generated by Django 5.1.4 on 2026-01-25 06:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acquisti", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordineacquisto",
            name="aliquota_iva",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("22.00"),
                help_text="Aliquota IVA in percentuale",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="ordineacquisto",
            name="imponibile",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Importo imponibile (netto)",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="ordineacquisto",
            name="importo_iva",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Importo IVA calcolato",
                max_digits=15,
            ),
        ),
        migrations.AlterField(
            model_name="ordineacquisto",
            name="importo_totale",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Importo totale dell'ordine (imponibile + IVA)",
                max_digits=15,
            ),
        ),
    ]
