# Generated by Django 6.0.1 on 2026-01-17 11:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("anagrafica", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocStabilimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_documento",
                    models.CharField(
                        help_text="Nome identificativo del documento", max_length=200
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            (
                                "scia",
                                "SCIA (Segnalazione Certificata di Inizio Attività)",
                            ),
                            ("dia", "DIA (Dichiarazione di Inizio Attività)"),
                            ("autorizzazione", "Autorizzazione Edilizia"),
                            ("permesso_costruire", "Permesso di Costruire"),
                            ("contratto_derattizzazione", "Contratto Derattizzazione"),
                            ("contratto_disinfestazione", "Contratto Disinfestazione"),
                            ("contratto_pulizie", "Contratto Pulizie"),
                            ("contratto_vigilanza", "Contratto Vigilanza"),
                            ("contratto_manutenzione", "Contratto Manutenzione"),
                            (
                                "cert_prevenzione_incendi",
                                "Certificato Prevenzione Incendi",
                            ),
                            ("cert_agibilita", "Certificato di Agibilità"),
                            ("cert_conformita", "Certificato di Conformità"),
                            ("collaudo_impianti", "Collaudo Impianti"),
                            ("verifica_ascensori", "Verifica Ascensori"),
                            ("controllo_caldaie", "Controllo Caldaie"),
                            ("controllo_antincendio", "Controllo Sistemi Antincendio"),
                            ("aut_emissioni", "Autorizzazione Emissioni"),
                            ("gestione_rifiuti", "Autorizzazione Gestione Rifiuti"),
                            ("planimetria", "Planimetria"),
                            ("denuncia", "Denuncia/Comunicazione"),
                            ("rapporto", "Rapporto Tecnico"),
                            ("verbale", "Verbale Controllo"),
                            ("contratto", "Contratto Generico"),
                            ("certificazione", "Certificazione Generica"),
                            ("altro", "Altro"),
                        ],
                        default="altro",
                        help_text="Tipologia del documento",
                        max_length=30,
                    ),
                ),
                (
                    "versione",
                    models.CharField(
                        default="1.0", help_text="Versione del documento", max_length=10
                    ),
                ),
                (
                    "descrizione",
                    models.TextField(
                        blank=True,
                        help_text="Descrizione del contenuto del documento",
                        null=True,
                    ),
                ),
                (
                    "file_documento",
                    models.FileField(
                        help_text="File del documento",
                        upload_to="documenti_stabilimenti/%Y/%m/",
                    ),
                ),
                (
                    "data_documento",
                    models.DateField(
                        blank=True,
                        help_text="Data del documento (se diversa dalla data di caricamento)",
                        null=True,
                    ),
                ),
                (
                    "data_scadenza",
                    models.DateField(
                        blank=True,
                        help_text="Data di scadenza del documento (se applicabile)",
                        null=True,
                    ),
                ),
                (
                    "attivo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se il documento è ancora valido/attivo",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, help_text="Note aggiuntive sul documento", null=True
                    ),
                ),
                ("data_inserimento", models.DateTimeField(auto_now_add=True)),
                ("data_modifica", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Documento Stabilimento",
                "verbose_name_plural": "Documenti Stabilimenti",
                "ordering": ["-data_inserimento"],
            },
        ),
        migrations.CreateModel(
            name="Stabilimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome identificativo dello stabilimento",
                        max_length=200,
                    ),
                ),
                (
                    "codice_stabilimento",
                    models.CharField(
                        help_text="Codice univoco per identificazione rapida",
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("indirizzo", models.CharField(max_length=300)),
                (
                    "cap",
                    models.CharField(
                        max_length=5,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Il CAP deve essere di 5 cifre",
                                regex="^\\d{5}$",
                            )
                        ],
                    ),
                ),
                ("citta", models.CharField(max_length=100)),
                (
                    "provincia",
                    models.CharField(
                        max_length=2,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Provincia deve essere di 2 lettere maiuscole",
                                regex="^[A-Z]{2}$",
                            )
                        ],
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True,
                        help_text="Telefono principale dello stabilimento",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "email_filiale",
                    models.EmailField(
                        blank=True,
                        help_text="Email principale dello stabilimento",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "superficie_mq",
                    models.PositiveIntegerField(
                        blank=True, help_text="Superficie in metri quadrati", null=True
                    ),
                ),
                (
                    "numero_piani",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Numero di piani dell'edificio"
                    ),
                ),
                (
                    "anno_costruzione",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Anno di costruzione dell'edificio",
                        null=True,
                    ),
                ),
                (
                    "attivo",
                    models.BooleanField(
                        default=True, help_text="Indica se lo stabilimento è attivo"
                    ),
                ),
                (
                    "data_apertura",
                    models.DateField(
                        blank=True,
                        help_text="Data di apertura/attivazione dello stabilimento",
                        null=True,
                    ),
                ),
                (
                    "data_chiusura",
                    models.DateField(
                        blank=True,
                        help_text="Data di chiusura (se applicabile)",
                        null=True,
                    ),
                ),
                (
                    "note_generali",
                    models.TextField(
                        blank=True,
                        help_text="Note generali sullo stabilimento",
                        null=True,
                    ),
                ),
                ("data_creazione", models.DateTimeField(auto_now_add=True)),
                ("data_modifica", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Stabilimento",
                "verbose_name_plural": "Stabilimenti",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="CostiStabilimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_pratica",
                    models.CharField(
                        help_text="Numero pratica generato automaticamente",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "causale",
                    models.CharField(
                        choices=[
                            ("manutenzione_ordinaria", "Manutenzione Ordinaria"),
                            (
                                "manutenzione_straordinaria",
                                "Manutenzione Straordinaria",
                            ),
                            ("adeguamento", "Adeguamento Strutturale"),
                            ("servizi_periodici", "Servizi Periodici"),
                            ("certificazioni", "Certificazioni Obbligatorie"),
                            ("energia_elettrica", "Energia Elettrica"),
                            ("gas_naturale", "Gas Naturale"),
                            ("acqua", "Acqua e Scarichi"),
                            ("telefonia", "Telefonia e Internet"),
                            ("rifiuti", "Smaltimento Rifiuti"),
                            ("sicurezza", "Sicurezza e Vigilanza"),
                            ("pulizie", "Servizi di Pulizia"),
                            ("assicurazioni", "Assicurazioni"),
                            ("tasse", "Tasse e Tributi"),
                            ("altro", "Altro"),
                        ],
                        default="servizi_periodici",
                        max_length=50,
                        verbose_name="Tipologia Costo",
                    ),
                ),
                (
                    "stato",
                    models.CharField(
                        choices=[
                            ("preventivo", "Preventivo"),
                            ("approvato", "Approvato"),
                            ("in_corso", "In Corso"),
                            ("completato", "Completato"),
                            ("fatturato", "Fatturato"),
                            ("pagato", "Pagato"),
                        ],
                        default="preventivo",
                        max_length=20,
                        verbose_name="Stato della Pratica",
                    ),
                ),
                (
                    "titolo",
                    models.CharField(
                        help_text="Titolo/oggetto dell'intervento o servizio",
                        max_length=200,
                    ),
                ),
                (
                    "descrizione",
                    models.TextField(
                        help_text="Descrizione dettagliata dell'intervento"
                    ),
                ),
                (
                    "importo",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Importo del costo",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "iva_percentuale",
                    models.DecimalField(
                        decimal_places=2,
                        default=22,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="IVA %",
                    ),
                ),
                (
                    "data_richiesta",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Data della richiesta/preventivo",
                    ),
                ),
                (
                    "data_inizio_lavori",
                    models.DateField(
                        blank=True,
                        help_text="Data inizio intervento/servizio",
                        null=True,
                    ),
                ),
                (
                    "data_fine_lavori",
                    models.DateField(
                        blank=True, help_text="Data fine intervento/servizio", null=True
                    ),
                ),
                (
                    "data_fattura",
                    models.DateField(
                        blank=True, help_text="Data della fattura", null=True
                    ),
                ),
                (
                    "data_scadenza_servizio",
                    models.DateField(
                        blank=True,
                        help_text="Data del prossimo intervento programmato o scadenza certificazione",
                        null=True,
                        verbose_name="Prossima Scadenza",
                    ),
                ),
                (
                    "fattura",
                    models.FileField(
                        blank=True,
                        help_text="File della fattura",
                        null=True,
                        upload_to="fatture_stabilimenti/%Y/%m/",
                    ),
                ),
                (
                    "preventivo",
                    models.FileField(
                        blank=True,
                        help_text="File del preventivo",
                        null=True,
                        upload_to="preventivi_stabilimenti/%Y/%m/",
                    ),
                ),
                (
                    "certificato",
                    models.FileField(
                        blank=True,
                        help_text="Certificato o documento ufficiale",
                        null=True,
                        upload_to="certificati_stabilimenti/%Y/%m/",
                    ),
                ),
                (
                    "allegato1",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="allegati_stabilimenti/%Y/%m/",
                        verbose_name="Allegato 1",
                    ),
                ),
                (
                    "allegato2",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="allegati_stabilimenti/%Y/%m/",
                        verbose_name="Allegato 2",
                    ),
                ),
                (
                    "allegato3",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="allegati_stabilimenti/%Y/%m/",
                        verbose_name="Allegato 3",
                    ),
                ),
                (
                    "note_interne",
                    models.TextField(
                        blank=True,
                        help_text="Note interne non visibili nei documenti",
                        null=True,
                    ),
                ),
                ("data_creazione", models.DateTimeField(auto_now_add=True)),
                ("data_modifica", models.DateTimeField(auto_now=True)),
                (
                    "consumo_kwh",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "consumo_mc",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("periodo_fatturazione_da", models.DateField(blank=True, null=True)),
                ("periodo_fatturazione_a", models.DateField(blank=True, null=True)),
                (
                    "codice_pdr_pod",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "fornitore",
                    models.ForeignKey(
                        help_text="Fornitore del servizio/lavoro",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="costi_stabilimenti",
                        to="anagrafica.fornitore",
                    ),
                ),
            ],
            options={
                "verbose_name": "Costo Stabilimento",
                "verbose_name_plural": "Costi Stabilimenti",
                "ordering": ["-data_creazione"],
            },
        ),
    ]
