# Generated by Django 6.0.1 on 2026-01-17 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stabilimenti", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="costistabilimento",
            name="incaricato",
            field=models.ForeignKey(
                help_text="Responsabile interno della pratica",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="costi_gestiti",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="docstabilimento",
            name="caricato_da",
            field=models.ForeignKey(
                help_text="Utente che ha caricato il documento",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documenti_caricati",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stabilimento",
            name="creato_da",
            field=models.ForeignKey(
                help_text="Utente che ha creato lo stabilimento (automatico)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stabilimenti_creati",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stabilimento",
            name="modificato_da",
            field=models.ForeignKey(
                blank=True,
                help_text="Ultimo utente che ha modificato lo stabilimento",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stabilimenti_modificati",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stabilimento",
            name="responsabile_amministrativo",
            field=models.ForeignKey(
                blank=True,
                help_text="Responsabile amministrativo dello stabilimento (scelto manualmente)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stabilimenti_amministrativi",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stabilimento",
            name="responsabile_operativo",
            field=models.ForeignKey(
                blank=True,
                help_text="Responsabile operativo dello stabilimento (scelto manualmente)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stabilimenti_operativi",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="docstabilimento",
            name="stabilimento",
            field=models.ForeignKey(
                help_text="Stabilimento di riferimento",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documenti",
                to="stabilimenti.stabilimento",
            ),
        ),
        migrations.AddField(
            model_name="costistabilimento",
            name="stabilimento",
            field=models.ForeignKey(
                help_text="Stabilimento di riferimento",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="costi",
                to="stabilimenti.stabilimento",
            ),
        ),
        migrations.AddIndex(
            model_name="stabilimento",
            index=models.Index(fields=["attivo"], name="stabiliment_attivo_5a5210_idx"),
        ),
        migrations.AddIndex(
            model_name="stabilimento",
            index=models.Index(
                fields=["codice_stabilimento"], name="stabiliment_codice__3450ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stabilimento",
            index=models.Index(
                fields=["responsabile_operativo"], name="stabiliment_respons_a21798_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stabilimento",
            index=models.Index(
                fields=["responsabile_amministrativo"],
                name="stabiliment_respons_239e66_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stabilimento",
            index=models.Index(fields=["citta"], name="stabiliment_citta_acf5f6_idx"),
        ),
        migrations.AddIndex(
            model_name="docstabilimento",
            index=models.Index(
                fields=["stabilimento", "tipo_documento"],
                name="stabiliment_stabili_044e11_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="docstabilimento",
            index=models.Index(
                fields=["data_scadenza"], name="stabiliment_data_sc_71f4e1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="docstabilimento",
            index=models.Index(fields=["attivo"], name="stabiliment_attivo_4e0026_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="docstabilimento",
            unique_together={("stabilimento", "nome_documento", "versione")},
        ),
        migrations.AddIndex(
            model_name="costistabilimento",
            index=models.Index(
                fields=["stabilimento", "causale"],
                name="stabiliment_stabili_4d2eee_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="costistabilimento",
            index=models.Index(
                fields=["data_scadenza_servizio"], name="stabiliment_data_sc_1016e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="costistabilimento",
            index=models.Index(fields=["stato"], name="stabiliment_stato_18852b_idx"),
        ),
        migrations.AddIndex(
            model_name="costistabilimento",
            index=models.Index(
                fields=["fornitore"], name="stabiliment_fornito_462b07_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="costistabilimento",
            index=models.Index(
                fields=["data_fattura"], name="stabiliment_data_fa_6685ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="costistabilimento",
            index=models.Index(
                fields=["numero_pratica"], name="stabiliment_numero__613300_idx"
            ),
        ),
    ]
