# Generated by Django 5.1.4 on 2026-02-21 08:02

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("anagrafica", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ListaProdotti",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Data creazione"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Data modifica"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Attivo"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data cancellazione"
                    ),
                ),
                (
                    "nome_lista",
                    models.CharField(
                        help_text="Es: Setup Principale, Backup, Extra",
                        max_length=200,
                        verbose_name="Nome Lista",
                    ),
                ),
                (
                    "descrizione",
                    models.TextField(blank=True, verbose_name="Descrizione"),
                ),
                (
                    "approvata",
                    models.BooleanField(default=False, verbose_name="Approvata"),
                ),
                (
                    "data_approvazione",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data Approvazione"
                    ),
                ),
                (
                    "stato",
                    models.CharField(
                        choices=[
                            ("bozza", "Bozza"),
                            ("in_revisione", "In Revisione"),
                            ("approvata", "Approvata"),
                            ("rifiutata", "Rifiutata"),
                        ],
                        default="bozza",
                        max_length=20,
                        verbose_name="Stato",
                    ),
                ),
                (
                    "note_approvazione",
                    models.TextField(blank=True, verbose_name="Note Approvazione"),
                ),
                (
                    "approvata_da",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="liste_prodotti_approvate",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approvata da",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creato da",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modificato da",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lista Prodotti",
                "verbose_name_plural": "Liste Prodotti",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProdottoLista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codice_prodotto",
                    models.CharField(
                        help_text="Codice univoco del prodotto",
                        max_length=100,
                        verbose_name="Codice Prodotto",
                    ),
                ),
                (
                    "nome_prodotto",
                    models.CharField(max_length=200, verbose_name="Nome Prodotto"),
                ),
                (
                    "categoria_prodotto",
                    models.CharField(
                        blank=True,
                        help_text="Es: Casse, Microfoni, Videocamere, Fari, etc.",
                        max_length=100,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "quantita",
                    models.PositiveIntegerField(default=1, verbose_name="Quantità"),
                ),
                (
                    "lunghezza_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Lunghezza (cm)",
                    ),
                ),
                (
                    "larghezza_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Larghezza (cm)",
                    ),
                ),
                (
                    "altezza_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Altezza (cm)",
                    ),
                ),
                (
                    "peso_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Peso (kg)",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Note")),
                (
                    "priorita",
                    models.CharField(
                        choices=[
                            ("normale", "Normale"),
                            ("alta", "Alta"),
                            ("critica", "Critica"),
                        ],
                        default="normale",
                        max_length=10,
                        verbose_name="Priorità",
                    ),
                ),
                (
                    "lista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prodotti",
                        to="progetti_eventi.listaprodotti",
                        verbose_name="Lista",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prodotto Lista",
                "verbose_name_plural": "Prodotti Lista",
                "ordering": ["categoria_prodotto", "nome_prodotto"],
            },
        ),
        migrations.CreateModel(
            name="Progetto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Data creazione"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Data modifica"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Attivo"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data cancellazione"
                    ),
                ),
                (
                    "codice",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=50,
                        unique=True,
                        verbose_name="Codice",
                    ),
                ),
                (
                    "nome_evento",
                    models.CharField(
                        help_text="Es: Matrimonio Rossi, Concerto Estate 2026",
                        max_length=200,
                        verbose_name="Nome Evento",
                    ),
                ),
                (
                    "tipo_evento",
                    models.CharField(
                        choices=[
                            ("matrimonio", "Matrimonio"),
                            ("concerto", "Concerto"),
                            ("conferenza", "Conferenza"),
                            ("fiera", "Fiera"),
                            ("festival", "Festival"),
                            ("corporate", "Corporate Event"),
                            ("teatro", "Teatro"),
                            ("sport", "Evento Sportivo"),
                            ("televisione", "Produzione TV"),
                            ("altro", "Altro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo Evento",
                    ),
                ),
                (
                    "descrizione_evento",
                    models.TextField(
                        blank=True,
                        help_text="Descrizione dettagliata dell'evento",
                        verbose_name="Descrizione Evento",
                    ),
                ),
                ("data_evento", models.DateField(verbose_name="Data Evento")),
                (
                    "ora_inizio_evento",
                    models.TimeField(blank=True, null=True, verbose_name="Ora Inizio"),
                ),
                (
                    "data_fine_evento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Fine Evento"
                    ),
                ),
                (
                    "ora_fine_evento",
                    models.TimeField(blank=True, null=True, verbose_name="Ora Fine"),
                ),
                (
                    "location",
                    models.CharField(max_length=300, verbose_name="Nome Location"),
                ),
                (
                    "indirizzo_location",
                    models.TextField(verbose_name="Indirizzo Location"),
                ),
                (
                    "cap_location",
                    models.CharField(blank=True, max_length=10, verbose_name="CAP"),
                ),
                (
                    "citta_location",
                    models.CharField(max_length=100, verbose_name="Città"),
                ),
                (
                    "provincia_location",
                    models.CharField(
                        blank=True, max_length=2, verbose_name="Provincia"
                    ),
                ),
                (
                    "nazione_location",
                    models.CharField(
                        default="Italia", max_length=50, verbose_name="Nazione"
                    ),
                ),
                (
                    "coordinate_location",
                    models.CharField(
                        blank=True,
                        help_text="Formato: lat,lng",
                        max_length=100,
                        verbose_name="Coordinate GPS",
                    ),
                ),
                (
                    "data_consegna_richiesta",
                    models.DateTimeField(
                        help_text="Quando la merce deve essere consegnata alla location",
                        verbose_name="Data/Ora Consegna Richiesta",
                    ),
                ),
                (
                    "data_ritiro_richiesta",
                    models.DateTimeField(
                        help_text="Quando la merce deve essere ritirata dalla location",
                        verbose_name="Data/Ora Ritiro Richiesta",
                    ),
                ),
                (
                    "note_logistica_iniziali",
                    models.TextField(
                        blank=True,
                        help_text="Indicazioni preliminari per la logistica (accessi, vincoli, etc.)",
                        verbose_name="Note Logistica Iniziali",
                    ),
                ),
                (
                    "reparti_coinvolti",
                    models.JSONField(
                        default=list,
                        help_text="Lista reparti: ['audio', 'video', 'luci']",
                        verbose_name="Reparti Coinvolti",
                    ),
                ),
                (
                    "stato",
                    models.CharField(
                        choices=[
                            ("bozza", "Bozza"),
                            ("in_engineering", "In Engineering"),
                            ("engineering_completato", "Engineering Completato"),
                            ("in_preparazione", "In Preparazione"),
                            ("pronto", "Pronto"),
                            ("in_corso", "Evento in Corso"),
                            ("completato", "Completato"),
                            ("annullato", "Annullato"),
                        ],
                        default="bozza",
                        max_length=30,
                        verbose_name="Stato Progetto",
                    ),
                ),
                (
                    "budget_preventivato",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Budget totale del progetto",
                        max_digits=10,
                        null=True,
                        verbose_name="Budget Preventivato",
                    ),
                ),
                (
                    "budget_approvato",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Budget Approvato Cliente",
                    ),
                ),
                (
                    "note_commerciali",
                    models.TextField(
                        blank=True,
                        help_text="Note riservate al team commerciale",
                        verbose_name="Note Commerciali",
                    ),
                ),
                (
                    "priorita",
                    models.CharField(
                        choices=[
                            ("bassa", "Bassa"),
                            ("normale", "Normale"),
                            ("alta", "Alta"),
                            ("urgente", "Urgente"),
                        ],
                        default="normale",
                        max_length=10,
                        verbose_name="Priorità",
                    ),
                ),
                (
                    "data_invio_engineering",
                    models.DateTimeField(
                        blank=True,
                        help_text="Quando il progetto è stato inviato agli ingegneri",
                        null=True,
                        verbose_name="Data Invio Engineering",
                    ),
                ),
                (
                    "data_completamento_engineering",
                    models.DateTimeField(
                        blank=True,
                        help_text="Quando tutti gli engineering sono stati completati",
                        null=True,
                        verbose_name="Data Completamento Engineering",
                    ),
                ),
                (
                    "data_evento_concluso",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data Conclusione Evento"
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="progetti_eventi",
                        to="anagrafica.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "commerciale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="progetti_eventi_commerciale",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Commerciale Responsabile",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creato da",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modificato da",
                    ),
                ),
            ],
            options={
                "verbose_name": "Progetto Evento",
                "verbose_name_plural": "Progetti Eventi",
                "ordering": ["-data_evento", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProgettoReparto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Data creazione"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Data modifica"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Attivo"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data cancellazione"
                    ),
                ),
                (
                    "tipo_reparto",
                    models.CharField(
                        choices=[
                            ("audio", "Audio"),
                            ("video", "Video"),
                            ("luci", "Luci"),
                        ],
                        max_length=10,
                        verbose_name="Reparto",
                    ),
                ),
                (
                    "engineering_stato",
                    models.CharField(
                        choices=[
                            ("da_assegnare", "Da Assegnare"),
                            ("assegnato", "Assegnato"),
                            ("in_studio", "In Studio"),
                            ("completato", "Completato"),
                        ],
                        default="da_assegnare",
                        max_length=20,
                        verbose_name="Stato Engineering",
                    ),
                ),
                (
                    "engineering_completato",
                    models.BooleanField(
                        default=False,
                        help_text="True quando l'ingegnere ha completato lo studio e approvato le liste prodotti",
                        verbose_name="Engineering Completato",
                    ),
                ),
                (
                    "data_assegnazione_engineering",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Data Assegnazione Engineering",
                    ),
                ),
                (
                    "data_completamento_engineering",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Data Completamento Engineering",
                    ),
                ),
                (
                    "note_engineering",
                    models.TextField(
                        blank=True,
                        help_text="Note tecniche dell'ingegnere",
                        verbose_name="Note Engineering",
                    ),
                ),
                (
                    "magazzino_ready",
                    models.BooleanField(
                        default=False,
                        help_text="True quando tutti i prodotti sono approntati",
                        verbose_name="Magazzino Pronto",
                    ),
                ),
                (
                    "logistica_ready",
                    models.BooleanField(
                        default=False,
                        help_text="True quando consegna/ritiro sono pianificati",
                        verbose_name="Logistica Pronta",
                    ),
                ),
                (
                    "travel_ready",
                    models.BooleanField(
                        default=False,
                        help_text="True quando tutti i viaggi sono organizzati",
                        verbose_name="Travel Pronto",
                    ),
                ),
                (
                    "scouting_ready",
                    models.BooleanField(
                        default=False,
                        help_text="True quando tutto il personale è stato trovato",
                        verbose_name="Scouting Completato",
                    ),
                ),
                (
                    "numero_tecnici_necessari",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Definito dall'engineering",
                        verbose_name="Numero Tecnici Necessari",
                    ),
                ),
                (
                    "numero_facchini_necessari",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Definito dall'engineering",
                        verbose_name="Numero Facchini Necessari",
                    ),
                ),
                (
                    "metri_cubi_totali",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Calcolato automaticamente dalle liste prodotti",
                        max_digits=8,
                        verbose_name="Metri Cubi Totali",
                    ),
                ),
                (
                    "peso_totale_kg",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Calcolato automaticamente dalle liste prodotti",
                        max_digits=8,
                        verbose_name="Peso Totale (kg)",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creato da",
                    ),
                ),
                (
                    "engineering_assegnato_a",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ingegnere responsabile dello studio di questo reparto",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="progetti_engineering_assegnati",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ingegnere Assegnato",
                    ),
                ),
                (
                    "progetto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reparti",
                        to="progetti_eventi.progetto",
                        verbose_name="Progetto",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modificato da",
                    ),
                ),
            ],
            options={
                "verbose_name": "Progetto Reparto",
                "verbose_name_plural": "Progetti Reparti",
                "ordering": ["progetto", "tipo_reparto"],
            },
        ),
        migrations.AddField(
            model_name="listaprodotti",
            name="progetto_reparto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="liste_prodotti",
                to="progetti_eventi.progettoreparto",
                verbose_name="Progetto Reparto",
            ),
        ),
        migrations.CreateModel(
            name="EngineeringTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Data creazione"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Data modifica"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Attivo"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data cancellazione"
                    ),
                ),
                (
                    "titolo",
                    models.CharField(max_length=200, verbose_name="Titolo Task"),
                ),
                (
                    "descrizione",
                    models.TextField(blank=True, verbose_name="Descrizione"),
                ),
                (
                    "stato",
                    models.CharField(
                        choices=[
                            ("da_iniziare", "Da Iniziare"),
                            ("in_corso", "In Corso"),
                            ("completato", "Completato"),
                        ],
                        default="da_iniziare",
                        max_length=20,
                        verbose_name="Stato",
                    ),
                ),
                (
                    "data_inizio",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data Inizio"
                    ),
                ),
                (
                    "data_completamento",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data Completamento"
                    ),
                ),
                (
                    "ore_stimate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Ore Stimate",
                    ),
                ),
                (
                    "ore_effettive",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Ore Effettive",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Note")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creato da",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modificato da",
                    ),
                ),
                (
                    "progetto_reparto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engineering_tasks",
                        to="progetti_eventi.progettoreparto",
                        verbose_name="Progetto Reparto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Engineering Task",
                "verbose_name_plural": "Engineering Tasks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="progetto",
            index=models.Index(fields=["stato"], name="progetti_ev_stato_69b88e_idx"),
        ),
        migrations.AddIndex(
            model_name="progetto",
            index=models.Index(
                fields=["data_evento"], name="progetti_ev_data_ev_426efc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="progetto",
            index=models.Index(
                fields=["commerciale"], name="progetti_ev_commerc_668921_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="progetto",
            index=models.Index(
                fields=["cliente"], name="progetti_ev_cliente_987a18_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="progettoreparto",
            index=models.Index(
                fields=["progetto", "tipo_reparto"],
                name="progetti_ev_progett_858fa0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="progettoreparto",
            index=models.Index(
                fields=["engineering_assegnato_a"],
                name="progetti_ev_enginee_f19060_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="progettoreparto",
            index=models.Index(
                fields=["engineering_stato"], name="progetti_ev_enginee_d3dc25_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="progettoreparto",
            unique_together={("progetto", "tipo_reparto")},
        ),
        migrations.AddIndex(
            model_name="listaprodotti",
            index=models.Index(
                fields=["progetto_reparto", "approvata"],
                name="progetti_ev_progett_b4f81b_idx",
            ),
        ),
    ]
