# Generated by Django 5.1.4 on 2026-02-22 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0003_promemoria_assegnato_a_alter_promemoria_user"),
        ("progetti_eventi", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="progetto",
            name="chat_progetto",
            field=models.OneToOneField(
                blank=True,
                help_text="Chat di gruppo automatica per questo progetto",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="progetto",
                to="mail.chatconversation",
                verbose_name="Chat Progetto",
            ),
        ),
        migrations.AddField(
            model_name="progetto",
            name="partecipanti",
            field=models.ManyToManyField(
                blank=True,
                help_text="Utenti che partecipano al progetto e alla chat",
                related_name="progetti_partecipati",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Partecipanti Progetto",
            ),
        ),
    ]
