# Generated by Django 5.1.4 on 2026-02-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automezzi", "0003_automezzo_carta_carburante_and_more"),
        ("progetti_eventi", "0002_progetto_chat_progetto_progetto_partecipanti"),
    ]

    operations = [
        migrations.AddField(
            model_name="progetto",
            name="mezzi_assegnati",
            field=models.ManyToManyField(
                blank=True,
                help_text="Mezzi necessari per questo progetto (consegna/ritiro)",
                related_name="progetti_assegnati",
                to="automezzi.automezzo",
                verbose_name="Mezzi Assegnati",
            ),
        ),
    ]
