# Generated by Django 6.0.1 on 2026-01-17 11:38

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatConversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Data creazione"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Data modifica"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Attivo"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data cancellazione"
                    ),
                ),
                (
                    "titolo",
                    models.CharField(
                        blank=True,
                        help_text="Opzionale per chat dirette",
                        max_length=200,
                        verbose_name="Titolo Conversazione",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("direct", "Diretta (1-to-1)"), ("group", "Gruppo")],
                        default="direct",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(default=False, verbose_name="Archiviata"),
                ),
                (
                    "is_muted",
                    models.BooleanField(default=False, verbose_name="Silenziata"),
                ),
                (
                    "last_message_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Ultimo Messaggio",
                    ),
                ),
                (
                    "messages_count",
                    models.IntegerField(
                        default=0, editable=False, verbose_name="N. Messaggi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversazione Chat",
                "verbose_name_plural": "Conversazioni Chat",
                "ordering": ["-last_message_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Data creazione"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Data modifica"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Attivo"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data cancellazione"
                    ),
                ),
                ("contenuto", models.TextField(verbose_name="Contenuto")),
                (
                    "is_edited",
                    models.BooleanField(default=False, verbose_name="Modificato"),
                ),
                (
                    "edited_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Modificato il"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Eliminato"),
                ),
                (
                    "reactions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="{'👍': [user_id1, user_id2], '❤️': [user_id3]}",
                        verbose_name="Reazioni",
                    ),
                ),
            ],
            options={
                "verbose_name": "Messaggio Chat",
                "verbose_name_plural": "Messaggi Chat",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Data creazione"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Data modifica"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Attivo"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data cancellazione"
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Nome che apparirà come mittente",
                        max_length=200,
                        verbose_name="Nome Visualizzato",
                    ),
                ),
                (
                    "email_address",
                    models.EmailField(
                        help_text="Indirizzo email completo",
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="Indirizzo Email",
                    ),
                ),
                (
                    "smtp_server",
                    models.CharField(max_length=255, verbose_name="Server SMTP"),
                ),
                (
                    "smtp_port",
                    models.IntegerField(
                        default=587,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(65535),
                        ],
                        verbose_name="Porta SMTP",
                    ),
                ),
                (
                    "smtp_username",
                    models.CharField(max_length=255, verbose_name="Username SMTP"),
                ),
                (
                    "smtp_password",
                    models.CharField(
                        help_text="TODO: Criptare con django-cryptography",
                        max_length=255,
                        verbose_name="Password SMTP",
                    ),
                ),
                ("use_tls", models.BooleanField(default=True, verbose_name="Usa TLS")),
                ("use_ssl", models.BooleanField(default=False, verbose_name="Usa SSL")),
                (
                    "imap_server",
                    models.CharField(
                        blank=True,
                        help_text="Server per ricezione email",
                        max_length=255,
                        verbose_name="Server IMAP",
                    ),
                ),
                (
                    "imap_port",
                    models.IntegerField(
                        default=993,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(65535),
                        ],
                        verbose_name="Porta IMAP",
                    ),
                ),
                (
                    "imap_username",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Username IMAP"
                    ),
                ),
                (
                    "imap_password",
                    models.CharField(
                        blank=True,
                        help_text="TODO: Criptare",
                        max_length=255,
                        verbose_name="Password IMAP",
                    ),
                ),
                (
                    "imap_use_tls",
                    models.BooleanField(default=False, verbose_name="IMAP usa TLS"),
                ),
                (
                    "imap_use_ssl",
                    models.BooleanField(default=True, verbose_name="IMAP usa SSL"),
                ),
                (
                    "imap_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Abilita ricezione automatica email",
                        verbose_name="IMAP Abilitato",
                    ),
                ),
                (
                    "last_imap_sync",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Ultima Sincronizzazione IMAP",
                    ),
                ),
                (
                    "last_imap_error",
                    models.TextField(blank=True, verbose_name="Ultimo Errore IMAP"),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Configurazione testata con successo",
                        verbose_name="Configurazione Verificata",
                    ),
                ),
                (
                    "last_test_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ultimo Test"
                    ),
                ),
                (
                    "last_error",
                    models.TextField(blank=True, verbose_name="Ultimo Errore"),
                ),
                (
                    "daily_limit",
                    models.IntegerField(
                        default=500,
                        help_text="Numero massimo email/giorno",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Limite Giornaliero",
                    ),
                ),
                (
                    "hourly_limit",
                    models.IntegerField(
                        default=50,
                        help_text="Numero massimo email/ora",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Limite Orario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configurazione Email",
                "verbose_name_plural": "Configurazioni Email",
                "ordering": ["user__username"],
            },
        ),
        migrations.CreateModel(
            name="EmailFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Data creazione"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Data modifica"),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nome Cartella"),
                ),
                (
                    "folder_type",
                    models.CharField(
                        choices=[
                            ("inbox", "Posta in Arrivo"),
                            ("sent", "Inviati"),
                            ("drafts", "Bozze"),
                            ("trash", "Cestino"),
                            ("spam", "Spam"),
                            ("archive", "Archivio"),
                            ("custom", "Personalizzata"),
                        ],
                        default="custom",
                        max_length=20,
                        verbose_name="Tipo Cartella",
                    ),
                ),
                (
                    "total_messages",
                    models.IntegerField(default=0, verbose_name="Totale Messaggi"),
                ),
                (
                    "unread_messages",
                    models.IntegerField(default=0, verbose_name="Non Letti"),
                ),
            ],
            options={
                "verbose_name": "Cartella Email",
                "verbose_name_plural": "Cartelle Email",
                "ordering": ["folder_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="EmailLabel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Data creazione"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Data modifica"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Attivo"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data cancellazione"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nome Etichetta"),
                ),
                ("slug", models.SlugField(max_length=100, verbose_name="Slug")),
                (
                    "color",
                    models.CharField(
                        default="#4285f4",
                        help_text="Colore esadecimale es. #4285f4",
                        max_length=7,
                        verbose_name="Colore",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="tag",
                        help_text="Nome icona Bootstrap Icons (es. 'tag', 'star')",
                        max_length=50,
                        verbose_name="Icona",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Ordine")),
                (
                    "is_visible",
                    models.BooleanField(default=True, verbose_name="Visibile"),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False, verbose_name="Etichetta Sistema"
                    ),
                ),
                (
                    "message_count",
                    models.IntegerField(
                        default=0, editable=False, verbose_name="N. Messaggi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Etichetta Email",
                "verbose_name_plural": "Etichette Email",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Data creazione"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Data modifica"),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("send", "Invio"),
                            ("receive", "Ricezione"),
                            ("sync", "Sincronizzazione"),
                            ("error", "Errore"),
                            ("config", "Configurazione"),
                            ("test", "Test"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Tipo Evento",
                    ),
                ),
                (
                    "event_description",
                    models.CharField(max_length=500, verbose_name="Descrizione"),
                ),
                (
                    "event_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Dati Evento"
                    ),
                ),
                ("success", models.BooleanField(default=True, verbose_name="Successo")),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Messaggio Errore"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Indirizzo IP"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="User Agent"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Data/Ora",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log Email",
                "verbose_name_plural": "Log Email",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="EmailMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Data creazione"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Data modifica"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Attivo"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data cancellazione"
                    ),
                ),
                (
                    "message_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Message-ID header del server",
                        max_length=500,
                        verbose_name="Message-ID",
                    ),
                ),
                (
                    "thread_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID conversazione",
                        max_length=500,
                        verbose_name="Thread ID",
                    ),
                ),
                (
                    "server_uid",
                    models.CharField(
                        blank=True,
                        help_text="UID del messaggio sul server IMAP",
                        max_length=100,
                        verbose_name="Server UID",
                    ),
                ),
                (
                    "to_addresses",
                    models.JSONField(
                        default=list,
                        help_text="Lista email destinatari",
                        verbose_name="Destinatari",
                    ),
                ),
                (
                    "cc_addresses",
                    models.JSONField(blank=True, default=list, verbose_name="CC"),
                ),
                (
                    "bcc_addresses",
                    models.JSONField(blank=True, default=list, verbose_name="BCC"),
                ),
                (
                    "from_address",
                    models.EmailField(max_length=254, verbose_name="Da (Email)"),
                ),
                (
                    "from_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Da (Nome)"
                    ),
                ),
                (
                    "reply_to",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Reply-To"
                    ),
                ),
                ("subject", models.CharField(max_length=998, verbose_name="Oggetto")),
                (
                    "content_html",
                    models.TextField(blank=True, verbose_name="Contenuto HTML"),
                ),
                (
                    "content_text",
                    models.TextField(blank=True, verbose_name="Contenuto Testo"),
                ),
                (
                    "content_size",
                    models.IntegerField(
                        default=0,
                        editable=False,
                        verbose_name="Dimensione Contenuto (bytes)",
                    ),
                ),
                (
                    "has_attachments",
                    models.BooleanField(default=False, verbose_name="Ha Allegati"),
                ),
                (
                    "attachments_info",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Metadata allegati per quick access",
                        verbose_name="Info Allegati",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("incoming", "In Arrivo"), ("outgoing", "In Uscita")],
                        db_index=True,
                        default="outgoing",
                        max_length=20,
                        verbose_name="Direzione",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Bozza"),
                            ("pending", "In Attesa"),
                            ("queued", "In Coda"),
                            ("sending", "Invio in Corso"),
                            ("sent", "Inviato"),
                            ("delivered", "Consegnato"),
                            ("failed", "Fallito"),
                            ("bounced", "Respinto"),
                            ("received", "Ricevuto"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="Stato",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Letto"
                    ),
                ),
                (
                    "is_flagged",
                    models.BooleanField(default=False, verbose_name="Importante"),
                ),
                ("is_spam", models.BooleanField(default=False, verbose_name="Spam")),
                (
                    "smtp_response",
                    models.TextField(blank=True, verbose_name="Risposta SMTP"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Messaggio Errore"),
                ),
                (
                    "delivery_attempts",
                    models.IntegerField(default=0, verbose_name="Tentativi Consegna"),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ID Oggetto Collegato"
                    ),
                ),
                (
                    "related_description",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        verbose_name="Descrizione Collegamento",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Inviato il"
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ricevuto il"
                    ),
                ),
            ],
            options={
                "verbose_name": "Messaggio Email",
                "verbose_name_plural": "Messaggi Email",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailQueue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Data creazione"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Data modifica"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Attivo"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data cancellazione"
                    ),
                ),
                (
                    "to_addresses",
                    models.JSONField(default=list, verbose_name="Destinatari"),
                ),
                (
                    "cc_addresses",
                    models.JSONField(blank=True, default=list, verbose_name="CC"),
                ),
                (
                    "bcc_addresses",
                    models.JSONField(blank=True, default=list, verbose_name="BCC"),
                ),
                ("subject", models.CharField(max_length=998, verbose_name="Oggetto")),
                (
                    "content_html",
                    models.TextField(blank=True, verbose_name="Contenuto HTML"),
                ),
                (
                    "content_text",
                    models.TextField(blank=True, verbose_name="Contenuto Testo"),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=5,
                        help_text="1=massima, 10=minima",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Priorità",
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Programmato per",
                    ),
                ),
                (
                    "max_attempts",
                    models.IntegerField(default=3, verbose_name="Max Tentativi"),
                ),
                (
                    "attempt_count",
                    models.IntegerField(default=0, verbose_name="Tentativi Effettuati"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "In Attesa"),
                            ("processing", "In Elaborazione"),
                            ("sent", "Inviato"),
                            ("failed", "Fallito"),
                            ("cancelled", "Annullato"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Stato",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Messaggio Errore"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Inviato il"
                    ),
                ),
                ("object_id", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "Email in Coda",
                "verbose_name_plural": "Email in Coda",
                "ordering": ["priority", "scheduled_at", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Data creazione"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Data modifica"),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Data"
                    ),
                ),
                (
                    "emails_sent",
                    models.IntegerField(default=0, verbose_name="Email Inviate"),
                ),
                (
                    "emails_failed",
                    models.IntegerField(default=0, verbose_name="Email Fallite"),
                ),
                (
                    "emails_bounced",
                    models.IntegerField(default=0, verbose_name="Email Respinte"),
                ),
                (
                    "emails_received",
                    models.IntegerField(default=0, verbose_name="Email Ricevute"),
                ),
                (
                    "preventivi_sent",
                    models.IntegerField(default=0, verbose_name="Preventivi Inviati"),
                ),
                (
                    "automezzi_sent",
                    models.IntegerField(default=0, verbose_name="Automezzi Inviati"),
                ),
                (
                    "acquisti_sent",
                    models.IntegerField(default=0, verbose_name="Acquisti Inviati"),
                ),
                ("hr_sent", models.IntegerField(default=0, verbose_name="HR Inviati")),
                (
                    "comunicazioni_sent",
                    models.IntegerField(
                        default=0, verbose_name="Comunicazioni Inviate"
                    ),
                ),
            ],
            options={
                "verbose_name": "Statistiche Email",
                "verbose_name_plural": "Statistiche Email",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Data creazione"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Data modifica"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Attivo"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data cancellazione"
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Nome Template"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="Slug"),
                ),
                (
                    "descrizione",
                    models.TextField(blank=True, verbose_name="Descrizione"),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("preventivi", "Preventivi"),
                            ("automezzi", "Automezzi"),
                            ("stabilimenti", "Stabilimenti"),
                            ("acquisti", "Acquisti"),
                            ("fatturazione", "Fatturazione"),
                            ("anagrafica", "Anagrafica"),
                            ("hr", "Risorse Umane"),
                            ("comunicazioni", "Comunicazioni"),
                            ("sistema", "Sistema"),
                            ("generico", "Generico"),
                        ],
                        default="generico",
                        max_length=50,
                        verbose_name="Categoria",
                    ),
                ),
                ("subject", models.CharField(max_length=500, verbose_name="Oggetto")),
                (
                    "content_html",
                    models.TextField(
                        help_text="Supporta variabili {{nome_variabile}}",
                        verbose_name="Contenuto HTML",
                    ),
                ),
                (
                    "content_text",
                    models.TextField(
                        blank=True,
                        help_text="Versione testo semplice (opzionale)",
                        verbose_name="Contenuto Testo",
                    ),
                ),
                (
                    "available_variables",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista variabili: ['nome', 'cognome', 'azienda']",
                        verbose_name="Variabili Disponibili",
                    ),
                ),
                (
                    "sample_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dati esempio per preview: {'nome': 'Mario', 'cognome': 'Rossi'}",
                        verbose_name="Dati Esempio",
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="Template di sistema (non modificabile)",
                        verbose_name="Template Sistema",
                    ),
                ),
                (
                    "usage_count",
                    models.IntegerField(
                        default=0, editable=False, verbose_name="Utilizzi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Template Email",
                "verbose_name_plural": "Template Email",
                "ordering": ["categoria", "nome"],
            },
        ),
        migrations.CreateModel(
            name="Promemoria",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Data creazione"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Data modifica"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Attivo"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data cancellazione"
                    ),
                ),
                ("titolo", models.CharField(max_length=200, verbose_name="Titolo")),
                (
                    "descrizione",
                    models.TextField(blank=True, verbose_name="Descrizione"),
                ),
                (
                    "priorita",
                    models.CharField(
                        choices=[
                            ("bassa", "Bassa"),
                            ("media", "Media"),
                            ("alta", "Alta"),
                            ("urgente", "Urgente"),
                        ],
                        default="media",
                        max_length=20,
                        verbose_name="Priorità",
                    ),
                ),
                (
                    "stato",
                    models.CharField(
                        choices=[
                            ("pending", "In Attesa"),
                            ("in_progress", "In Corso"),
                            ("completed", "Completato"),
                            ("cancelled", "Annullato"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Stato",
                    ),
                ),
                (
                    "data_scadenza",
                    models.DateTimeField(
                        blank=True,
                        help_text="Scadenza promemoria",
                        null=True,
                        verbose_name="Data Scadenza",
                    ),
                ),
                (
                    "completato_il",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completato il"
                    ),
                ),
                (
                    "notifica_email",
                    models.BooleanField(
                        default=False,
                        help_text="Invia email alla scadenza",
                        verbose_name="Notifica Email",
                    ),
                ),
                (
                    "notifica_giorni_prima",
                    models.IntegerField(
                        default=1,
                        help_text="Giorni prima della scadenza per notifica",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Giorni Preavviso",
                    ),
                ),
                (
                    "notificato",
                    models.BooleanField(default=False, verbose_name="Notifica Inviata"),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ID Oggetto Collegato"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista tag: ['lavoro', 'urgente', 'cliente']",
                        verbose_name="Tag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Promemoria",
                "verbose_name_plural": "Promemoria",
                "ordering": ["-data_scadenza", "-created_at"],
            },
        ),
    ]
