# Generated by Django 6.0.1 on 2026-01-17 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("mail", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chatconversation",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chat_conversations_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creata da",
            ),
        ),
        migrations.AddField(
            model_name="chatconversation",
            name="partecipanti",
            field=models.ManyToManyField(
                related_name="chat_conversations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Partecipanti",
            ),
        ),
        migrations.AddField(
            model_name="chatconversation",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modificato da",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="mail.chatconversation",
                verbose_name="Conversazione",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creato da",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="read_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="chat_messages_read",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Letto da",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="mail.chatmessage",
                verbose_name="In Risposta a",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_messages_sent",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Mittente",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modificato da",
            ),
        ),
        migrations.AddField(
            model_name="emailconfiguration",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creato da",
            ),
        ),
        migrations.AddField(
            model_name="emailconfiguration",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modificato da",
            ),
        ),
        migrations.AddField(
            model_name="emailconfiguration",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mail_config",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utente",
            ),
        ),
        migrations.AddField(
            model_name="emailfolder",
            name="config",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="folders",
                to="mail.emailconfiguration",
                verbose_name="Configurazione",
            ),
        ),
        migrations.AddField(
            model_name="emaillabel",
            name="configuration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="labels",
                to="mail.emailconfiguration",
                verbose_name="Configurazione",
            ),
        ),
        migrations.AddField(
            model_name="emaillabel",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creato da",
            ),
        ),
        migrations.AddField(
            model_name="emaillabel",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modificato da",
            ),
        ),
        migrations.AddField(
            model_name="emaillog",
            name="config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="logs",
                to="mail.emailconfiguration",
                verbose_name="Configurazione",
            ),
        ),
        migrations.AddField(
            model_name="emaillog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utente",
            ),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
                verbose_name="Tipo Oggetto Collegato",
            ),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creato da",
            ),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="mail.emailfolder",
                verbose_name="Cartella",
            ),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="labels",
            field=models.ManyToManyField(
                blank=True,
                related_name="messages",
                to="mail.emaillabel",
                verbose_name="Etichette",
            ),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="sender_config",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="mail.emailconfiguration",
                verbose_name="Configurazione Mittente",
            ),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modificato da",
            ),
        ),
        migrations.AddField(
            model_name="emaillog",
            name="message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="logs",
                to="mail.emailmessage",
                verbose_name="Messaggio",
            ),
        ),
        migrations.AddField(
            model_name="emailqueue",
            name="config",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="queued_messages",
                to="mail.emailconfiguration",
                verbose_name="Configurazione",
            ),
        ),
        migrations.AddField(
            model_name="emailqueue",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="emailqueue",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creato da",
            ),
        ),
        migrations.AddField(
            model_name="emailqueue",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modificato da",
            ),
        ),
        migrations.AddField(
            model_name="emailstats",
            name="config",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stats",
                to="mail.emailconfiguration",
                verbose_name="Configurazione",
            ),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creato da",
            ),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modificato da",
            ),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="template_used",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="mail.emailtemplate",
                verbose_name="Template Usato",
            ),
        ),
        migrations.AddField(
            model_name="promemoria",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
                verbose_name="Tipo Oggetto Collegato",
            ),
        ),
        migrations.AddField(
            model_name="promemoria",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creato da",
            ),
        ),
        migrations.AddField(
            model_name="promemoria",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modificato da",
            ),
        ),
        migrations.AddField(
            model_name="promemoria",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promemoria",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utente",
            ),
        ),
        migrations.AddIndex(
            model_name="chatconversation",
            index=models.Index(
                fields=["-last_message_at"], name="mail_chatco_last_me_a289b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="mail_chatme_convers_479fe4_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="emailfolder",
            unique_together={("config", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="emaillabel",
            unique_together={("configuration", "slug")},
        ),
        migrations.AddIndex(
            model_name="emaillog",
            index=models.Index(
                fields=["config", "event_type"], name="mail_emaill_config__83c75a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emaillog",
            index=models.Index(
                fields=["-timestamp"], name="mail_emaill_timesta_675e7c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailqueue",
            index=models.Index(
                fields=["status", "scheduled_at"], name="mail_emailq_status_f5622d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailqueue",
            index=models.Index(
                fields=["config", "status"], name="mail_emailq_config__52d97d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="emailstats",
            unique_together={("config", "date")},
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(
                fields=["sender_config", "folder"],
                name="mail_emailm_sender__2cdaaa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(
                fields=["message_id"], name="mail_emailm_message_31f09f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(
                fields=["direction", "status"], name="mail_emailm_directi_21db5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="mail_emailm_content_f82f4b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(
                fields=["-created_at"], name="mail_emailm_created_c1ba6c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="promemoria",
            index=models.Index(
                fields=["user", "stato"], name="mail_promem_user_id_0e69da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="promemoria",
            index=models.Index(
                fields=["data_scadenza"], name="mail_promem_data_sc_91aa65_idx"
            ),
        ),
    ]
