# Generated by Django 6.0.1 on 2026-01-18 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="promemoria",
            name="assegnato_a",
            field=models.ForeignKey(
                blank=True,
                help_text="Utente a cui è assegnato il promemoria. Se vuoto, assegnato al creatore.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promemoria_assegnati",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assegnato a",
            ),
        ),
        migrations.AlterField(
            model_name="promemoria",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promemoria",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creato da",
            ),
        ),
    ]
