# Generated by Django 5.1.4 on 2026-02-27 04:29

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0003_promemoria_assegnato_a_alter_promemoria_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="emailconfiguration",
            name="config_type",
            field=models.CharField(
                choices=[("personal", "Personale"), ("company", "Aziendale")],
                default="personal",
                help_text="Personale: usa le tue credenziali | Aziendale: usa server aziendale",
                max_length=20,
                verbose_name="Tipo Configurazione",
            ),
        ),
        migrations.AlterField(
            model_name="emailconfiguration",
            name="smtp_password",
            field=models.CharField(
                blank=True,
                help_text="Password per SMTP personale (TODO: Criptare con django-cryptography)",
                max_length=255,
                verbose_name="Password SMTP",
            ),
        ),
        migrations.AlterField(
            model_name="emailconfiguration",
            name="smtp_server",
            field=models.CharField(
                blank=True,
                help_text="Richiesto solo per configurazione personale",
                max_length=255,
                verbose_name="Server SMTP",
            ),
        ),
        migrations.AlterField(
            model_name="emailconfiguration",
            name="smtp_username",
            field=models.CharField(
                blank=True,
                help_text="Richiesto solo per configurazione personale",
                max_length=255,
                verbose_name="Username SMTP",
            ),
        ),
        migrations.CreateModel(
            name="CompanyEmailSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Data creazione"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Data modifica"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data cancellazione"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Es: 'Mail Aziendale', 'Server Primario'",
                        max_length=100,
                        verbose_name="Nome Configurazione",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Se disattivata, gli utenti non potranno usarla",
                        verbose_name="Attiva",
                    ),
                ),
                (
                    "smtp_server",
                    models.CharField(max_length=255, verbose_name="Server SMTP"),
                ),
                (
                    "smtp_port",
                    models.IntegerField(
                        default=587,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(65535),
                        ],
                        verbose_name="Porta SMTP",
                    ),
                ),
                (
                    "smtp_username",
                    models.CharField(
                        blank=True,
                        help_text="Lascia vuoto se non richiede autenticazione",
                        max_length=255,
                        verbose_name="Username SMTP",
                    ),
                ),
                (
                    "smtp_password",
                    models.CharField(
                        blank=True,
                        help_text="Password per autenticazione SMTP",
                        max_length=255,
                        verbose_name="Password SMTP",
                    ),
                ),
                ("use_tls", models.BooleanField(default=True, verbose_name="Usa TLS")),
                ("use_ssl", models.BooleanField(default=False, verbose_name="Usa SSL")),
                (
                    "allow_custom_from",
                    models.BooleanField(
                        default=True,
                        help_text="Permette agli utenti di usare la propria email come mittente",
                        verbose_name="Permetti From Personalizzato",
                    ),
                ),
                (
                    "default_from_domain",
                    models.CharField(
                        blank=True,
                        help_text="Es: @azienda.com - usato per validare email mittenti",
                        max_length=255,
                        verbose_name="Dominio Default",
                    ),
                ),
                (
                    "require_same_domain",
                    models.BooleanField(
                        default=False,
                        help_text="Gli utenti possono inviare solo con email dello stesso dominio aziendale",
                        verbose_name="Richiedi Stesso Dominio",
                    ),
                ),
                (
                    "daily_limit_per_user",
                    models.IntegerField(
                        blank=True,
                        help_text="Massimo numero di email che ogni utente può inviare al giorno",
                        null=True,
                        verbose_name="Limite Giornaliero per Utente",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Verificata"),
                ),
                (
                    "last_test_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ultimo Test"
                    ),
                ),
                (
                    "last_error",
                    models.TextField(blank=True, verbose_name="Ultimo Errore"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creato da",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modificato da",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configurazione Email Aziendale",
                "verbose_name_plural": "Configurazioni Email Aziendali",
                "ordering": ["-is_active", "name"],
            },
        ),
        migrations.AddField(
            model_name="emailconfiguration",
            name="company_settings",
            field=models.ForeignKey(
                blank=True,
                help_text="Server SMTP aziendale da utilizzare (solo se tipo=aziendale)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_configs",
                to="mail.companyemailsettings",
                verbose_name="Configurazione Aziendale",
            ),
        ),
    ]
