# Generated by Django 6.0.1 on 2026-01-21 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessioneAllestimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_evento', models.CharField(blank=True, max_length=255)),
                ('luogo', models.CharField(blank=True, max_length=255)),
                ('file_originale', models.FileField(blank=True, null=True, upload_to='allestimento/excel/')),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_completamento', models.DateTimeField(blank=True, null=True)),
                ('completata', models.BooleanField(default=False)),
                ('creato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessioni_allestimento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sessione Allestimento',
                'verbose_name_plural': 'Sessioni Allestimento',
                'ordering': ['-data_creazione'],
            },
        ),
        migrations.CreateModel(
            name='RigaProdotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('descrizione', models.CharField(max_length=500)),
                ('quantita_richiesta', models.PositiveIntegerField(default=0)),
                ('quantita_allestita', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True, max_length=2000)),
                ('completata', models.BooleanField(default=False)),
                ('data_completamento', models.DateTimeField(blank=True, null=True)),
                ('completata_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='righe_completate', to=settings.AUTH_USER_MODEL)),
                ('sessione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='righe', to='allestimento.sessioneallestimento')),
            ],
            options={
                'verbose_name': 'Riga Prodotto',
                'verbose_name_plural': 'Righe Prodotto',
                'ordering': ['ordine'],
            },
        ),
    ]
